{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v155",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v155.jar",
          "url": "natives-box2d-android-v155.jar",
          "size": 411485,
          "sha512": "045bd2ae3c791b5e9dc56e2cf211f65af77b682e02f314da7ae902ba1d66d5684d39163425a52000945c50e37f628bb50bf44f0c1a962cd6b59bfce579e5fbce",
          "sha256": "6635ed14f0d49affb387cf01deb675daf8bb31d7b5432fb7c5e5ceaf2b8b3506",
          "sha1": "48a33507da4226129ae1aa5a0d430b8e351b9f9c",
          "md5": "ee6a857630cc27b59dcc1543256bd386"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v155.jar",
          "url": "natives-box2d-android-v155.jar",
          "size": 411485,
          "sha512": "045bd2ae3c791b5e9dc56e2cf211f65af77b682e02f314da7ae902ba1d66d5684d39163425a52000945c50e37f628bb50bf44f0c1a962cd6b59bfce579e5fbce",
          "sha256": "6635ed14f0d49affb387cf01deb675daf8bb31d7b5432fb7c5e5ceaf2b8b3506",
          "sha1": "48a33507da4226129ae1aa5a0d430b8e351b9f9c",
          "md5": "ee6a857630cc27b59dcc1543256bd386"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v155-sources.jar",
          "url": "natives-box2d-android-v155-sources.jar",
          "size": 411485,
          "sha512": "5bab308763ca076bff8be2a884a58e2a5c77dbf27301b49e7135e1f24888d86eee1af9241932064aec440ac955c78ea0f846b390d61d3cf16c1c9ec9be202b03",
          "sha256": "2f319490f07444b84b3153c7aefc813507140baeea5c4901092c14c88406ce13",
          "sha1": "b707ab6418aa179f47b5c9fc2a06a1a269d32d07",
          "md5": "cd1a588c89d07257ba3bb7972be79cde"
        }
      ]
    }
  ]
}
