{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "core",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.yawk.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "54b75cbd1207ef1fd5cff517cbd188e763c85baa"
          }
        }
      ],
      "files": [
        {
          "name": "core-v156.1.jar",
          "url": "core-v156.1.jar",
          "size": 5645122,
          "sha512": "b72209d5635a1b231caadfd72ff161fc43b69c701156bbbfbc7b63db6995c013abf23b72730732bc441fe7b7a3e0990c49cc97f544702ebd03b27c46fc8b752b",
          "sha256": "90d93fe553676786b32cf90657cf19631ba8870b25ee1d8718223d0fc3124c9b",
          "sha1": "e46ec0b0058dccbdea27b214aac0907f3ba920b9",
          "md5": "9754419a1bb40f58dac69eb95fca72ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.yawk.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v156.1"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "54b75cbd1207ef1fd5cff517cbd188e763c85baa"
          }
        }
      ],
      "files": [
        {
          "name": "core-v156.1.jar",
          "url": "core-v156.1.jar",
          "size": 5645122,
          "sha512": "b72209d5635a1b231caadfd72ff161fc43b69c701156bbbfbc7b63db6995c013abf23b72730732bc441fe7b7a3e0990c49cc97f544702ebd03b27c46fc8b752b",
          "sha256": "90d93fe553676786b32cf90657cf19631ba8870b25ee1d8718223d0fc3124c9b",
          "sha1": "e46ec0b0058dccbdea27b214aac0907f3ba920b9",
          "md5": "9754419a1bb40f58dac69eb95fca72ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v156.1-sources.jar",
          "url": "core-v156.1-sources.jar",
          "size": 1528475,
          "sha512": "f4fc55b2152c1264270afdb867dae770334bec463c4749a19502f0d81d920eb7fa2ef32cb8116e6eddde22997a3a70be123dfe288fd2e30788d39170ece0a9a0",
          "sha256": "0c878ac56ca560861ebe38c7f21654324a2a53410696184e3c0c118698115434",
          "sha1": "51d2558fe9b229c82497bc5f56a081380c1a99e3",
          "md5": "658596f68a4066e7dec4272e42b347d5"
        }
      ]
    }
  ]
}
