{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v155.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v155.4.jar",
          "url": "backend-robovm-v155.4.jar",
          "size": 80682,
          "sha512": "6d104cfc93981a4edb06104c74346caed7f36b126dcc7e17d5bc531aded4dfe7296bb6d93529b8713deed5c2a4f8c6af01320b70818d8c741279c28344f4df9d",
          "sha256": "ae908f843959cdaebc44e5dca0793794b34420421ca84d05565d091a51fca08e",
          "sha1": "ace9db7f0b5ce0cb783aa6232a6ad083f5f23189",
          "md5": "ce0b5b61d0abfad673812ab5731fa089"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v155.4.jar",
          "url": "backend-robovm-v155.4.jar",
          "size": 80682,
          "sha512": "6d104cfc93981a4edb06104c74346caed7f36b126dcc7e17d5bc531aded4dfe7296bb6d93529b8713deed5c2a4f8c6af01320b70818d8c741279c28344f4df9d",
          "sha256": "ae908f843959cdaebc44e5dca0793794b34420421ca84d05565d091a51fca08e",
          "sha1": "ace9db7f0b5ce0cb783aa6232a6ad083f5f23189",
          "md5": "ce0b5b61d0abfad673812ab5731fa089"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v155.4-sources.jar",
          "url": "backend-robovm-v155.4-sources.jar",
          "size": 45852,
          "sha512": "02120be8058b30339af1b4cc72af4183bbff18f23a6a5c03cf9099f7bc9bddbbcc2899c8564b13bc02c24dce9e01eaeff006cb29664c4324e0d2b53c6d52f782",
          "sha256": "f216ad7263c77b354bc7c6bb56e60772b7c6f939c12787fd0d4523d441973c1b",
          "sha1": "6f839c37129d05cc30df4ddec2c26e6602071ee0",
          "md5": "357802904f98e806df3efbd210822106"
        }
      ]
    }
  ]
}
