{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v155.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v155.4.jar",
          "url": "backend-sdl-v155.4.jar",
          "size": 3812401,
          "sha512": "1820deb5bf04cd560b4e2d0176fbf3bef74d0b3e4ffacadadf41fb8f0255fe2b22f3570928abf46250b0612c51a9872d9a4d373f41070d9609bd11960cd2794c",
          "sha256": "982c91a3fc97a360e956d7b9f6f725e8552f560d1461c3752dcfce4923bd3e87",
          "sha1": "0551d68eb3747a7d6add01f0e10556a4a48e77ab",
          "md5": "caa827c5cd0fb08e8be40281499d35c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v155.4.jar",
          "url": "backend-sdl-v155.4.jar",
          "size": 3812401,
          "sha512": "1820deb5bf04cd560b4e2d0176fbf3bef74d0b3e4ffacadadf41fb8f0255fe2b22f3570928abf46250b0612c51a9872d9a4d373f41070d9609bd11960cd2794c",
          "sha256": "982c91a3fc97a360e956d7b9f6f725e8552f560d1461c3752dcfce4923bd3e87",
          "sha1": "0551d68eb3747a7d6add01f0e10556a4a48e77ab",
          "md5": "caa827c5cd0fb08e8be40281499d35c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v155.4-sources.jar",
          "url": "backend-sdl-v155.4-sources.jar",
          "size": 3793309,
          "sha512": "c2d94c518a12f38cc9e6c218ee40bdec512d89dc29ee3e6e6480cc87d12e55ba9d2430dbd0367a6d4dc033ba191418d9d06bccaacfa5993f2d5eaf32140da3b2",
          "sha256": "2f6d14cbf742dbec477dba73a6d0d9f7298fabfa417ee6563468b134ec6f1b38",
          "sha1": "8e4c83826855e0c32bd83230e384367d18eceb70",
          "md5": "8a80efb193aeafd4a8db6527fcf3407a"
        }
      ]
    }
  ]
}
