{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v155.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v155.2.jar",
          "url": "natives-box2d-android-v155.2.jar",
          "size": 411485,
          "sha512": "b35989ac492cb49c9427ec5d4dec9fc31b03ae58796fa536d814355a3151f57d7444c3ffe45cae1acd8e5a7aae96098133d9b3a29a3e9dd8348cb61453d6674a",
          "sha256": "d4d69d9fa06678f7ed81ed77a08fc4bba190a05b24f92f0fd8364474a67e02b6",
          "sha1": "70ec7acaac36db4840b9a87cc14e20f808a26f63",
          "md5": "5aec9f877224fd67686b222943bc7a12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v155.2.jar",
          "url": "natives-box2d-android-v155.2.jar",
          "size": 411485,
          "sha512": "b35989ac492cb49c9427ec5d4dec9fc31b03ae58796fa536d814355a3151f57d7444c3ffe45cae1acd8e5a7aae96098133d9b3a29a3e9dd8348cb61453d6674a",
          "sha256": "d4d69d9fa06678f7ed81ed77a08fc4bba190a05b24f92f0fd8364474a67e02b6",
          "sha1": "70ec7acaac36db4840b9a87cc14e20f808a26f63",
          "md5": "5aec9f877224fd67686b222943bc7a12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v155.2-sources.jar",
          "url": "natives-box2d-android-v155.2-sources.jar",
          "size": 411485,
          "sha512": "1ca82a6c9b8c511cdee811cafab581379577e40f0114e6702ae9e71386b9b0f0450863e7719c8a3f35b746097955de2a5e8f6b18decd523469507a6cfc1e1460",
          "sha256": "08363d51a73778622aaf989213e5702312eda886815c41822bdf6ddf8c89ef11",
          "sha1": "069d1ef44531b16193214db603347dec67f6964d",
          "md5": "e18d40c1aadce5fb4bf614ca6905864c"
        }
      ]
    }
  ]
}
