{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "packer",
    "version": "v154",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packer-v154.jar",
          "url": "packer-v154.jar",
          "size": 52630,
          "sha512": "a5c1bc9c0e35cf282eb6080a4afd9a1dcc8a2073d948d0de0d2a42558ecc344d36112e5642d50cc521e5f47092760382f5334f23d5a26fe94ae7113c835fa935",
          "sha256": "a87edeaf4f74fbedaa0d6225ad90b702663cb2bc686b24883e8d42ea9b92e926",
          "sha1": "5220ab46ebd0eb5085ebe978d86aaf271f355eb0",
          "md5": "424446c67d99cf773696b9e4bb1291d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packer-v154.jar",
          "url": "packer-v154.jar",
          "size": 52630,
          "sha512": "a5c1bc9c0e35cf282eb6080a4afd9a1dcc8a2073d948d0de0d2a42558ecc344d36112e5642d50cc521e5f47092760382f5334f23d5a26fe94ae7113c835fa935",
          "sha256": "a87edeaf4f74fbedaa0d6225ad90b702663cb2bc686b24883e8d42ea9b92e926",
          "sha1": "5220ab46ebd0eb5085ebe978d86aaf271f355eb0",
          "md5": "424446c67d99cf773696b9e4bb1291d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packer-v154-sources.jar",
          "url": "packer-v154-sources.jar",
          "size": 24170,
          "sha512": "51c05eb12a763de6a5477e7cdefdd2cfb57138199a04a53b513968ae9e51aa625b5963f8f2f36e7f247377edb76bc4294aae80f714f5cfea5bc66d17eedd6150",
          "sha256": "e1815735fab78f3296d559d8a616423032fb22b0f3090c30243feb868ce6e854",
          "sha1": "57a694e88595c33fe440663ae779949974ae2672",
          "md5": "0aee2b6df10a5116eccebe2cbbe2a1f5"
        }
      ]
    }
  ]
}
