{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "core",
    "version": "v149",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v149.jar",
          "url": "core-v149.jar",
          "size": 5327995,
          "sha512": "ecc6e3cc0b075b0a4d2a421ad9fa1c03429bee318f59e1c132d4213ec7907b6a113fa03931fcad76f363f97b79b36024bef2c29235f53dcdcc53f37cf3cc491f",
          "sha256": "d3bffe445903db2827c6f5d255ccb9fcdb3175b4ca19da328e817c81b6e7b144",
          "sha1": "b32bc7cd9e1335303b69902a5694b6d0e81c059d",
          "md5": "93cf2e4f769bdd43678f0572333acf60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "filedialogs",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v149"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v149.jar",
          "url": "core-v149.jar",
          "size": 5327995,
          "sha512": "ecc6e3cc0b075b0a4d2a421ad9fa1c03429bee318f59e1c132d4213ec7907b6a113fa03931fcad76f363f97b79b36024bef2c29235f53dcdcc53f37cf3cc491f",
          "sha256": "d3bffe445903db2827c6f5d255ccb9fcdb3175b4ca19da328e817c81b6e7b144",
          "sha1": "b32bc7cd9e1335303b69902a5694b6d0e81c059d",
          "md5": "93cf2e4f769bdd43678f0572333acf60"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v149-sources.jar",
          "url": "core-v149-sources.jar",
          "size": 1433276,
          "sha512": "d79078a6b5df33aeb2d7274a103f706526e4d8a872623f794533de3217856c3298aeddb031c17f68fbc77951b0f13afcf2b54ab09a045b93c54b0c619f4413f1",
          "sha256": "76129e25ece99ff5d9d3d766b1160c47455ef98ed4fc73cf58d0df73951140c8",
          "sha1": "0469ce340a0671603f84d41678606ce16e3d6fa3",
          "md5": "a18d02305368209e978e51a2c60e32a5"
        }
      ]
    }
  ]
}
