{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-ios",
    "version": "v155.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v155.4.jar",
          "url": "natives-box2d-ios-v155.4.jar",
          "size": 2384392,
          "sha512": "506edc7fbb67871416fa7b28f47db73e8db1aa3a578b1ad406b473d5e02cd1693d6088c64281c769d909746ab3de6858852e0386f6b19ba37033fa5714014a66",
          "sha256": "2b1801174b0a1dbe160967c82b1d60c8d18c83a1f8514c35e0d9ee0127b393e7",
          "sha1": "92ee606beaa60993802bcd0dc920c730a3efc428",
          "md5": "828c31b71df8f830479f0fc26ca0202d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v155.4.jar",
          "url": "natives-box2d-ios-v155.4.jar",
          "size": 2384392,
          "sha512": "506edc7fbb67871416fa7b28f47db73e8db1aa3a578b1ad406b473d5e02cd1693d6088c64281c769d909746ab3de6858852e0386f6b19ba37033fa5714014a66",
          "sha256": "2b1801174b0a1dbe160967c82b1d60c8d18c83a1f8514c35e0d9ee0127b393e7",
          "sha1": "92ee606beaa60993802bcd0dc920c730a3efc428",
          "md5": "828c31b71df8f830479f0fc26ca0202d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v155.4-sources.jar",
          "url": "natives-box2d-ios-v155.4-sources.jar",
          "size": 2384392,
          "sha512": "04f629f07a764b65bfc5da4d45aa65515eb53b2dd13feb961517a9d0544844ce4ea730fc84d4d7659b08fdc49bd3cfea573dd5766b7b422318abd846ccf2440b",
          "sha256": "3b823f4cdff98fe346dd3ae84ee2e0641982e4a7809f98cb833945eb186b7583",
          "sha1": "a46ee6f16a3433bca56a694e395e63825dd7b41f",
          "md5": "be6f44c6b05ed05871396a98a21cdc20"
        }
      ]
    }
  ]
}
