{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "recorder",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "recorder-v156.1.jar",
          "url": "recorder-v156.1.jar",
          "size": 5720,
          "sha512": "54af4989256d3a6e5bd52d18296e7aaeac932e89df8d3910d4393d06704ff6c79299fb44a74dc1711e98eb43af0ba705fc90c414c4c86feea022c7440980d7a6",
          "sha256": "55368df4994443fb4a0a6d64d0e6ae49058d168f231f9b07617e6a1df0c33a40",
          "sha1": "5b7b011114e822fef17aecd6e2a8cae56b701620",
          "md5": "508d20f24121cefce8382ad1510aef10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recorder-v156.1.jar",
          "url": "recorder-v156.1.jar",
          "size": 5720,
          "sha512": "54af4989256d3a6e5bd52d18296e7aaeac932e89df8d3910d4393d06704ff6c79299fb44a74dc1711e98eb43af0ba705fc90c414c4c86feea022c7440980d7a6",
          "sha256": "55368df4994443fb4a0a6d64d0e6ae49058d168f231f9b07617e6a1df0c33a40",
          "sha1": "5b7b011114e822fef17aecd6e2a8cae56b701620",
          "md5": "508d20f24121cefce8382ad1510aef10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recorder-v156.1-sources.jar",
          "url": "recorder-v156.1-sources.jar",
          "size": 2907,
          "sha512": "72fb544eff052c48d72c58b9aacb5eb013ecf251e3288c62adca2210edacf3c6c0281419993502cd0d9ac92ab7c2813230df157c4133cd9f930cf5cd54c61d4f",
          "sha256": "5bb3fc7c2de0e70863c6e6570262f594139c3067947cb96a8ee7042f08280cfc",
          "sha1": "f586aff668e4b3a9f5c28e395323d906d5dd052d",
          "md5": "b36e80b92d770bea2ed8053885ca752d"
        }
      ]
    }
  ]
}
