{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "recorder",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "recorder-v156.1.jar",
          "url": "recorder-v156.1.jar",
          "size": 5720,
          "sha512": "7a7c2e59b5b74b6203458cae3e3f62b15d5cedc27e7097c01588b2cdacab746a556e566d83689670d44982d864e47caef329d235743e533260557b929abc57ab",
          "sha256": "a632c9c29d2a9c75d6c6b6770fb776bcb20218b3b5a8532dc82d471c301e05b1",
          "sha1": "51271577f5dc176171772a031f4275d174945c86",
          "md5": "fa989a9a0695ecd925dda328edf1a1b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recorder-v156.1.jar",
          "url": "recorder-v156.1.jar",
          "size": 5720,
          "sha512": "7a7c2e59b5b74b6203458cae3e3f62b15d5cedc27e7097c01588b2cdacab746a556e566d83689670d44982d864e47caef329d235743e533260557b929abc57ab",
          "sha256": "a632c9c29d2a9c75d6c6b6770fb776bcb20218b3b5a8532dc82d471c301e05b1",
          "sha1": "51271577f5dc176171772a031f4275d174945c86",
          "md5": "fa989a9a0695ecd925dda328edf1a1b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recorder-v156.1-sources.jar",
          "url": "recorder-v156.1-sources.jar",
          "size": 2907,
          "sha512": "bd19c4324b4ba45e41d220dfe31b36310b7dfd4e4113d23c6af576190f0aa492e5c00ff6437748c7a6cd6ff0d14ab533a966f6e75817d58165eb5a0b0e8b4dd1",
          "sha256": "9bcd3d41af1c50b9fc461d8f987217df73d5bafb22b6627ae2035ec59bbfaec4",
          "sha1": "dc8f31e21d7db0e17e9fd8b6d19f08612792cb77",
          "md5": "9a089ed3fbb9eb880377ae921694d1ad"
        }
      ]
    }
  ]
}
