{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-desktop",
    "version": "v155",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v155.jar",
          "url": "natives-box2d-desktop-v155.jar",
          "size": 512159,
          "sha512": "59c00208867965698fe7011e50374fc4a7124593ecf6c600c37aec23b443041e74fcd9d457c629fddd469fdff6c21425bfccf75241ac33bb22854e4092260cd1",
          "sha256": "0af1ea1c400c9eb77586ac04dc477572ab60994c325fac8c18e5bd42c7d2833f",
          "sha1": "c8c3306ace8d9abe19bea5ee36fb4033a2333b12",
          "md5": "790a1fcca036267b3015f94390d07a06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v155.jar",
          "url": "natives-box2d-desktop-v155.jar",
          "size": 512159,
          "sha512": "59c00208867965698fe7011e50374fc4a7124593ecf6c600c37aec23b443041e74fcd9d457c629fddd469fdff6c21425bfccf75241ac33bb22854e4092260cd1",
          "sha256": "0af1ea1c400c9eb77586ac04dc477572ab60994c325fac8c18e5bd42c7d2833f",
          "sha1": "c8c3306ace8d9abe19bea5ee36fb4033a2333b12",
          "md5": "790a1fcca036267b3015f94390d07a06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v155-sources.jar",
          "url": "natives-box2d-desktop-v155-sources.jar",
          "size": 512159,
          "sha512": "6dc44898d86610640e6cbe9354dd0969774e891fa6c77f376430b7cc69282e7c84fcbd53de18b7dc770182e502ee0194e4e3447d3c801c0d3a04b04868693da3",
          "sha256": "03aa8ecdc556c430c31b7f49343273d862dc120ae6bfda4cd61c85357bd8e1d1",
          "sha1": "838bb48beb9da2bc10fda3f30d2161688a980d02",
          "md5": "e39d45d61a7bc8882592e0f4f17595d7"
        }
      ]
    }
  ]
}
