{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "packer",
    "version": "v155.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packer-v155.4.jar",
          "url": "packer-v155.4.jar",
          "size": 52630,
          "sha512": "b9a4f9600be28b661f1587f4c80051c5090540439c2dc2233cc407a8b86e830d140d2e2fa86dd969e8ff800fd204abd00a83b55fbb4ebfd2d2940f23c4e79a61",
          "sha256": "bad9dbc805a30f8cb20520b264ae9455f20070e855aebc11c6564402cbe80824",
          "sha1": "2514970c0efe576f6a28a69a0b796c6d5b92d83e",
          "md5": "517f9b1194fdbeaea4e1e6b60711171e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packer-v155.4.jar",
          "url": "packer-v155.4.jar",
          "size": 52630,
          "sha512": "b9a4f9600be28b661f1587f4c80051c5090540439c2dc2233cc407a8b86e830d140d2e2fa86dd969e8ff800fd204abd00a83b55fbb4ebfd2d2940f23c4e79a61",
          "sha256": "bad9dbc805a30f8cb20520b264ae9455f20070e855aebc11c6564402cbe80824",
          "sha1": "2514970c0efe576f6a28a69a0b796c6d5b92d83e",
          "md5": "517f9b1194fdbeaea4e1e6b60711171e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packer-v155.4-sources.jar",
          "url": "packer-v155.4-sources.jar",
          "size": 24170,
          "sha512": "a06f327d3764a4c1d17fa89931fddbff3a0e8f72233b3a3b88e91dc67feda578d5635c6cb980808d157a065db4774e277cd7b751f0a72bc62674dc0ed0e6d55f",
          "sha256": "f5dbfbfa203d58c28c1177a3b6f7be830798ee7ddd4ba173f16e9bca5b282e4d",
          "sha1": "f7c992fca010d1489f56803c5fe6864d1d8ecc47",
          "md5": "0978bd8c766a097294ba7b69f91cd37c"
        }
      ]
    }
  ]
}
