{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v149",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v149.jar",
          "url": "backend-sdl-v149.jar",
          "size": 3751183,
          "sha512": "6e17735a6406990ff018a70aae308cfe509a7c808cc5365e84850dc3563f5d2fb8c1693d2717ed298e7ab457eed60e1649038696961beaef2b06c1b85fe11111",
          "sha256": "3beaa45576b990a28ff9bf0a06d41acb51924b1230472aea30f8bbaeb3489ed1",
          "sha1": "3a374b5d27c28313b931ce8c29040c0f0976884e",
          "md5": "f22994e310ba0440b5480929327f4c5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v149.jar",
          "url": "backend-sdl-v149.jar",
          "size": 3751183,
          "sha512": "6e17735a6406990ff018a70aae308cfe509a7c808cc5365e84850dc3563f5d2fb8c1693d2717ed298e7ab457eed60e1649038696961beaef2b06c1b85fe11111",
          "sha256": "3beaa45576b990a28ff9bf0a06d41acb51924b1230472aea30f8bbaeb3489ed1",
          "sha1": "3a374b5d27c28313b931ce8c29040c0f0976884e",
          "md5": "f22994e310ba0440b5480929327f4c5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v149-sources.jar",
          "url": "backend-sdl-v149-sources.jar",
          "size": 3731614,
          "sha512": "e27e5a86e8d3c67255966ad62956879c0a39422b70e2ae2e4e5e4c2f5705105594f3626de726180ab2dbce4d73bf908fe8b09a2e16a81f7e07d2e0a92bdfe649",
          "sha256": "168c58c5d7b4ca1e98e917929c258fa40c152cf24ec0803c18a7b5f6defc72a4",
          "sha1": "efeb41d8cd3b0b9c6c506e7b58d5cf671d37f798",
          "md5": "995ff3e4905ec92710c6fd38ff88f2af"
        }
      ]
    }
  ]
}
