{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-desktop",
    "version": "v154.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v154.3.jar",
          "url": "natives-box2d-desktop-v154.3.jar",
          "size": 512159,
          "sha512": "7777a87e64f2058a039448e87d2b26a76693978114f069dde5fa19ab85464de5f4e4f05bc8a026e42c9d72102c9c48167b5e7eb6ff83dfe248c472287eb819fe",
          "sha256": "5321bd608d591a298ec57e1f5fc740db402ead44a1fcbba52b43d3ef0acdc386",
          "sha1": "048f8b6e5af8771c231d4da0a3c8786b0fe50be3",
          "md5": "76340c6fe8c37283aa573763fffe0815"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v154.3.jar",
          "url": "natives-box2d-desktop-v154.3.jar",
          "size": 512159,
          "sha512": "7777a87e64f2058a039448e87d2b26a76693978114f069dde5fa19ab85464de5f4e4f05bc8a026e42c9d72102c9c48167b5e7eb6ff83dfe248c472287eb819fe",
          "sha256": "5321bd608d591a298ec57e1f5fc740db402ead44a1fcbba52b43d3ef0acdc386",
          "sha1": "048f8b6e5af8771c231d4da0a3c8786b0fe50be3",
          "md5": "76340c6fe8c37283aa573763fffe0815"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v154.3-sources.jar",
          "url": "natives-box2d-desktop-v154.3-sources.jar",
          "size": 512159,
          "sha512": "defae05c93ce252ca51d0657f0122f3595345e8af269b63dc3f40459fceaa6828e7b12a4bc9e7e70616029dfd36fea456e50b510d7fad34605f831a8844a24b1",
          "sha256": "7b66a1bd76ef9a2ebbd10f22be79434a3cb1f817b82c11530d5365bdac07f640",
          "sha1": "143097cd7554068a0e298f563a143b7c4f22d1ce",
          "md5": "eb2fdbbc9328fc87f464836ddcb16860"
        }
      ]
    }
  ]
}
