{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v150",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v150.jar",
          "url": "backend-sdl-v150.jar",
          "size": 3812181,
          "sha512": "0454b260c07851b2c5197acb00960a49c6b4bad0c0e62542565a439febe14eb56cb742a533d8ab7496636b011f2258440667a91f7e361c16a30892e4e8cebade",
          "sha256": "7cb0d6b2ac4f21a7bfadbd0a18073f3c1673152db7205baefa5c907c3ef1fc69",
          "sha1": "292caa5659194f7f0de0a5f1d95c5a533644c003",
          "md5": "23c1531f163b3dccf7975f535feca433"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v150.jar",
          "url": "backend-sdl-v150.jar",
          "size": 3812181,
          "sha512": "0454b260c07851b2c5197acb00960a49c6b4bad0c0e62542565a439febe14eb56cb742a533d8ab7496636b011f2258440667a91f7e361c16a30892e4e8cebade",
          "sha256": "7cb0d6b2ac4f21a7bfadbd0a18073f3c1673152db7205baefa5c907c3ef1fc69",
          "sha1": "292caa5659194f7f0de0a5f1d95c5a533644c003",
          "md5": "23c1531f163b3dccf7975f535feca433"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v150-sources.jar",
          "url": "backend-sdl-v150-sources.jar",
          "size": 3793108,
          "sha512": "ec24ff91d36f1ae405384bf6e0daf90b552889c585a2a89a655c09c459fcaedba966fd4d0af7333a887f21493001964dd7c4c217b9b2f474d5b2d9c32b9220af",
          "sha256": "87d7cce322da73777d49814e52fec0087b36b3b3d9b44fd7a18abd53e0b87b70",
          "sha1": "ca9cad9f910f1b8e3235a9522a4ebd058e5033cb",
          "md5": "9a09b715683d4aff04796732345d1ae1"
        }
      ]
    }
  ]
}
