{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "g3d",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "g3d-v156.1.jar",
          "url": "g3d-v156.1.jar",
          "size": 45674,
          "sha512": "6dde41bb6479e80a4a48da012be6a3911afa21d35a10977b4d617f71f8119e1dfedf9061dd5e901cf66ddbbe7b4f5c21361b9538fdb3330ba2dcd5aec061fb35",
          "sha256": "8d340c1e8cca03bb8d32f7c37de0ff2956b6572266f728f43ee57fcfcd090458",
          "sha1": "d0070b06675c50dda3526a08217ae5702bfa393d",
          "md5": "3158eceb68df285880b9e87665f59e26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v156.1.jar",
          "url": "g3d-v156.1.jar",
          "size": 45674,
          "sha512": "6dde41bb6479e80a4a48da012be6a3911afa21d35a10977b4d617f71f8119e1dfedf9061dd5e901cf66ddbbe7b4f5c21361b9538fdb3330ba2dcd5aec061fb35",
          "sha256": "8d340c1e8cca03bb8d32f7c37de0ff2956b6572266f728f43ee57fcfcd090458",
          "sha1": "d0070b06675c50dda3526a08217ae5702bfa393d",
          "md5": "3158eceb68df285880b9e87665f59e26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v156.1-sources.jar",
          "url": "g3d-v156.1-sources.jar",
          "size": 35333,
          "sha512": "7ef3dec26f55fec9df4b2d4abcd72dc1ace44554217273c9ba479652f6602f1c8b9c15fbdade2ada5d601d22cd9cc466ba062cf67d85f4b49fb786050fa1977c",
          "sha256": "81f111bc6bb9c86e81fd34308022d88cf8c3f9c1a132fa17024e39b0c6e09a45",
          "sha1": "8e156adbfd1d76088377b8dc1a4883d7a2e20e3e",
          "md5": "97a41e1e93e4e2f6032e142c205122b3"
        }
      ]
    }
  ]
}
