{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-ios",
    "version": "v150.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-ios-v150.1.jar",
          "url": "natives-ios-v150.1.jar",
          "size": 4964339,
          "sha512": "768e8b15808b27f52d187b212ac51a9de6cd99789b259f03ae0b1535d71153bbd5b54684bd962eaf3d718ee7228ee4f282081f778952d5d964e15a8a0eb29ac3",
          "sha256": "6937156d4e848ba825378522bb4bff12ed46d7b891c423ad5682c1d5b6313232",
          "sha1": "455c2af9a96012d25a4286a5829dbc1a249f4a7c",
          "md5": "2b5ecee5d9be7f9807013c47e9311504"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-ios-v150.1.jar",
          "url": "natives-ios-v150.1.jar",
          "size": 4964339,
          "sha512": "768e8b15808b27f52d187b212ac51a9de6cd99789b259f03ae0b1535d71153bbd5b54684bd962eaf3d718ee7228ee4f282081f778952d5d964e15a8a0eb29ac3",
          "sha256": "6937156d4e848ba825378522bb4bff12ed46d7b891c423ad5682c1d5b6313232",
          "sha1": "455c2af9a96012d25a4286a5829dbc1a249f4a7c",
          "md5": "2b5ecee5d9be7f9807013c47e9311504"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-ios-v150.1-sources.jar",
          "url": "natives-ios-v150.1-sources.jar",
          "size": 4964339,
          "sha512": "5a0c1e6e7be65d6ebb4010f14331ffb975ccf28fefc7d8ffc22b1ef7f1ed7ecc157f650d4bdee09d1788af1c7af79aa68e8656479a2e196b24be322b64d10717",
          "sha256": "acba126c9cde87223b3e88c0a600eda895cd1a8bf7bdbc6da98e2ea92f676c0b",
          "sha1": "9e37b3a9bbc845cc5e00aacba8f74350e78f03c5",
          "md5": "12b93b6e1e3a18bfd5027d27b1895855"
        }
      ]
    }
  ]
}
