{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v150",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v150.jar",
          "url": "natives-box2d-android-v150.jar",
          "size": 411485,
          "sha512": "cf4990fa55923b09423d05bd394ff02b8112c9fe75eeb13bcefa9cf38ae04fe6386b2a9b9f42b560ceed6516caf9e305d98e12d7b54ca01b71050787196707cc",
          "sha256": "1859a46090acb397cc6791064819e182ab247e968726cc8b4dfa8d5a493f1801",
          "sha1": "e6400c472b9ace11b875e28bbf69fdbb0a4f84b2",
          "md5": "6b411614da51693905ba0df7cdc8cd6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v150.jar",
          "url": "natives-box2d-android-v150.jar",
          "size": 411485,
          "sha512": "cf4990fa55923b09423d05bd394ff02b8112c9fe75eeb13bcefa9cf38ae04fe6386b2a9b9f42b560ceed6516caf9e305d98e12d7b54ca01b71050787196707cc",
          "sha256": "1859a46090acb397cc6791064819e182ab247e968726cc8b4dfa8d5a493f1801",
          "sha1": "e6400c472b9ace11b875e28bbf69fdbb0a4f84b2",
          "md5": "6b411614da51693905ba0df7cdc8cd6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v150-sources.jar",
          "url": "natives-box2d-android-v150-sources.jar",
          "size": 411485,
          "sha512": "3fca7cf5d60edb19a3ab9afe26d1ba79b6f13cf5bdfcb12ae3e3a38c6b64acdaefb016e5ba236cc5566af7cfb1f6eb0fb793ec41fc32b579e9d6d987590acaac",
          "sha256": "096bdce31eb40d8b8ee79b51346f1b9accdd2251fb8564392f08925ea4dbc690",
          "sha1": "ae7e7defc60f5a1c610584234ec711183d08fc38",
          "md5": "4a909316638af3a8d0dac76840a38de8"
        }
      ]
    }
  ]
}
