{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v155.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v155.2.jar",
          "url": "backend-robovm-v155.2.jar",
          "size": 80682,
          "sha512": "f6b13170046d5f3bb4b6de400098fee086bc927df4baae8f3ce574ac7c0454dbbaf9ad48862be2c4e7767ba9740ac60be6253154fada235ef9e4aa1bd5531adb",
          "sha256": "72ef687422a5a964eb9a7abbb3cb54b74f1842cb078e0575822d6e45130b6480",
          "sha1": "b595cec850df037f82dca2d1a234b9e0687a529c",
          "md5": "f4d789ae789e6aeba8a8c404af408222"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v155.2.jar",
          "url": "backend-robovm-v155.2.jar",
          "size": 80682,
          "sha512": "f6b13170046d5f3bb4b6de400098fee086bc927df4baae8f3ce574ac7c0454dbbaf9ad48862be2c4e7767ba9740ac60be6253154fada235ef9e4aa1bd5531adb",
          "sha256": "72ef687422a5a964eb9a7abbb3cb54b74f1842cb078e0575822d6e45130b6480",
          "sha1": "b595cec850df037f82dca2d1a234b9e0687a529c",
          "md5": "f4d789ae789e6aeba8a8c404af408222"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v155.2-sources.jar",
          "url": "backend-robovm-v155.2-sources.jar",
          "size": 45852,
          "sha512": "e563fbb5208699ca685645f09d7a6c2f9fb97d4fed86d2b2609b402557997b24a240678a43233349d2c4bd30ca786c32d3c6620a8fd80d61cee99b10a057c206",
          "sha256": "fef85ccffae4b84caea83f96884ec354b8155398e4920baa64c2f81ef497725a",
          "sha1": "d1f4f638cd9810af597678c4ac9842eb96adbfa2",
          "md5": "45b4cfb617f615134154eb051d634b5d"
        }
      ]
    }
  ]
}
