{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "fx",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fx-v156.1.jar",
          "url": "fx-v156.1.jar",
          "size": 62586,
          "sha512": "9f4624517ebea1b61377c0cc2cc33718864c8b6defe5d6e5c3da6ce51ba15fbcaf0804c8b39398c18a7a40d030be67a89da722d668bc1c30ac144c4f3c8bd935",
          "sha256": "48b33968e90b3abde3014f9d32e07fc08244edd6c78d75f839b1bf54b0407ccb",
          "sha1": "51cea7dba06a7968b24dc018cd6de9e9d7d9dfd9",
          "md5": "4e490b7b0498505eeeb054472312888c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fx-v156.1.jar",
          "url": "fx-v156.1.jar",
          "size": 62586,
          "sha512": "9f4624517ebea1b61377c0cc2cc33718864c8b6defe5d6e5c3da6ce51ba15fbcaf0804c8b39398c18a7a40d030be67a89da722d668bc1c30ac144c4f3c8bd935",
          "sha256": "48b33968e90b3abde3014f9d32e07fc08244edd6c78d75f839b1bf54b0407ccb",
          "sha1": "51cea7dba06a7968b24dc018cd6de9e9d7d9dfd9",
          "md5": "4e490b7b0498505eeeb054472312888c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fx-v156.1-sources.jar",
          "url": "fx-v156.1-sources.jar",
          "size": 40350,
          "sha512": "485a9f9cee757a5197eb283a1f2be2da8048067c6e663972d7a6952bc08203df3a0dcc46452f178805483f08b07774fc9dfd79c4ff2755df83237ca978460de4",
          "sha256": "3527ff5dde1fa705e02aa04d0539f20d28d10fa4f6ed048c112b06ec047e7b23",
          "sha1": "31c8ada044a56e51aa466930ec32099884114516",
          "md5": "f7de4c20f444c857d93b15a20b0abe44"
        }
      ]
    }
  ]
}
