{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v152.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v152.2.jar",
          "url": "natives-box2d-android-v152.2.jar",
          "size": 411485,
          "sha512": "9cb3db7f77c225480099aa04d2331fc4ab5c38b1da4b35b126ba6ca9c8e6f17910af8aafd46e8d55db2b5ddb9b6220a1d8571d9d2ea78098253f5e1f893c8240",
          "sha256": "cf280b3fb7824f87af793e4e03a9e228aba87ca24de3f5316e0c923aec7256c1",
          "sha1": "074adce3e9a3e61a2d26976c72a8243f6a8d88da",
          "md5": "db6d82a65d80d263d6dabcadcf0a3be0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v152.2.jar",
          "url": "natives-box2d-android-v152.2.jar",
          "size": 411485,
          "sha512": "9cb3db7f77c225480099aa04d2331fc4ab5c38b1da4b35b126ba6ca9c8e6f17910af8aafd46e8d55db2b5ddb9b6220a1d8571d9d2ea78098253f5e1f893c8240",
          "sha256": "cf280b3fb7824f87af793e4e03a9e228aba87ca24de3f5316e0c923aec7256c1",
          "sha1": "074adce3e9a3e61a2d26976c72a8243f6a8d88da",
          "md5": "db6d82a65d80d263d6dabcadcf0a3be0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v152.2-sources.jar",
          "url": "natives-box2d-android-v152.2-sources.jar",
          "size": 411485,
          "sha512": "ff65fbba8a2444c847202aeb407c8aed1ddd1b9e40d33dfeee4dfcf5af86df91f61fa5e62c3308837da7ad03ec4f567c3aef4ee07d5382838bbc8e5b3bde074f",
          "sha256": "c7c1ea73e634334d2b38b7e67a2bd5833e2165589fa73cd1515ecc6cf793002d",
          "sha1": "811ca9616d20044487d6026cd9bed505759e6758",
          "md5": "1567109451645d0ee1c948c56bcc94ba"
        }
      ]
    }
  ]
}
