{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v150.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v150.1.jar",
          "url": "natives-box2d-android-v150.1.jar",
          "size": 411485,
          "sha512": "24a492a5868ca6c1c76f0b895f63de0592f1edf94483f0779ada8130adac543d1332d8e84465d0af76a4073f6bf69a8824f67b5c2ec5942dd379f9621aba5ce3",
          "sha256": "7ed6896f9f62471a5ff8cf9fd90ca7ac55f29223e459513ecbe6280fec77fcf6",
          "sha1": "2624c31c32abac95d74d9803c2ca58ac0bb7c543",
          "md5": "b85d4ee50593599a1c06b42067461d7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v150.1.jar",
          "url": "natives-box2d-android-v150.1.jar",
          "size": 411485,
          "sha512": "24a492a5868ca6c1c76f0b895f63de0592f1edf94483f0779ada8130adac543d1332d8e84465d0af76a4073f6bf69a8824f67b5c2ec5942dd379f9621aba5ce3",
          "sha256": "7ed6896f9f62471a5ff8cf9fd90ca7ac55f29223e459513ecbe6280fec77fcf6",
          "sha1": "2624c31c32abac95d74d9803c2ca58ac0bb7c543",
          "md5": "b85d4ee50593599a1c06b42067461d7a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v150.1-sources.jar",
          "url": "natives-box2d-android-v150.1-sources.jar",
          "size": 411485,
          "sha512": "2d08937d8a5601dde04f1ef91c28aee80a355f687465da536f99f063344ed34c9b966e3d3e11516b3bc18c530877075cc2ef0d161161309edb87f69c4f739684",
          "sha256": "e90f37a3849bcec974fff331a0de0ccd42aa6c04716396ac9a129e3f96e30d12",
          "sha1": "5e8f8eac2a39209bee75ea9a3140a380fc50c0f0",
          "md5": "f5a98e167d881686bdf815a6ea9c5261"
        }
      ]
    }
  ]
}
