{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v155",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v155.jar",
          "url": "backends-v155.jar",
          "size": 261,
          "sha512": "2ced5dab1822ad268ee305ee981f16b2a5538ee687cbea2b6faad3196a48545693d2066d77bd871b22f6b7308c5e1640e34ecb3bae10a03069db09b50cf862bc",
          "sha256": "17b3b82eb7378b2bc61941a66bd98153cb756fbaef803d843109415be991fbda",
          "sha1": "8f5ec72f074b8900f5552c11249e7e790180aae7",
          "md5": "3bad59fe41d8347ff40ed3c350f2af33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v155.jar",
          "url": "backends-v155.jar",
          "size": 261,
          "sha512": "2ced5dab1822ad268ee305ee981f16b2a5538ee687cbea2b6faad3196a48545693d2066d77bd871b22f6b7308c5e1640e34ecb3bae10a03069db09b50cf862bc",
          "sha256": "17b3b82eb7378b2bc61941a66bd98153cb756fbaef803d843109415be991fbda",
          "sha1": "8f5ec72f074b8900f5552c11249e7e790180aae7",
          "md5": "3bad59fe41d8347ff40ed3c350f2af33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v155-sources.jar",
          "url": "backends-v155-sources.jar",
          "size": 261,
          "sha512": "2ced5dab1822ad268ee305ee981f16b2a5538ee687cbea2b6faad3196a48545693d2066d77bd871b22f6b7308c5e1640e34ecb3bae10a03069db09b50cf862bc",
          "sha256": "17b3b82eb7378b2bc61941a66bd98153cb756fbaef803d843109415be991fbda",
          "sha1": "8f5ec72f074b8900f5552c11249e7e790180aae7",
          "md5": "3bad59fe41d8347ff40ed3c350f2af33"
        }
      ]
    }
  ]
}
