{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v151",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v151.jar",
          "url": "backend-sdl-v151.jar",
          "size": 3812481,
          "sha512": "1e60a14cc9991975b147edaa5b0c246551b137ffa8e23d733229bf38e5004294a58b36678afa7411ddc280265d23e4eaee88ca609b61557d255393d989f772bb",
          "sha256": "9100e4748262af6b2207807661e6943eb972f37bc083db322200191b27b4635c",
          "sha1": "92ca0a677fa3f413d17cbd2e0084ad6945d4a2c6",
          "md5": "ae55ceeedffb4273313335d7974c6216"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v151.jar",
          "url": "backend-sdl-v151.jar",
          "size": 3812481,
          "sha512": "1e60a14cc9991975b147edaa5b0c246551b137ffa8e23d733229bf38e5004294a58b36678afa7411ddc280265d23e4eaee88ca609b61557d255393d989f772bb",
          "sha256": "9100e4748262af6b2207807661e6943eb972f37bc083db322200191b27b4635c",
          "sha1": "92ca0a677fa3f413d17cbd2e0084ad6945d4a2c6",
          "md5": "ae55ceeedffb4273313335d7974c6216"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v151-sources.jar",
          "url": "backend-sdl-v151-sources.jar",
          "size": 3793260,
          "sha512": "755f59ac92fdb6dcdacccea85c6efa836a069316f6a8097c1ff451e5a107d149537e216fe766c6487d76c7c67c1f6198812d57d23eb00ac0233f4ddd5d4ee1cc",
          "sha256": "4003c4c55e4ea0711d9c102d9d7ac025a89ec14c9dc5be09c4b9ff4caf69f97e",
          "sha1": "0edf4a84c18d9616f8f5be236b3fab8e2fa46365",
          "md5": "1daaf8c77ea94d54a26595e4917d949b"
        }
      ]
    }
  ]
}
