{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v150",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v150.jar",
          "url": "natives-freetype-desktop-v150.jar",
          "size": 1098026,
          "sha512": "e6ac6bcf92703c4b49f6c993e25bbcce787b42d657a2797342e7795a6d1be4aabdc710314ad968a252995a449a69fb935be38af2a9d39c0623f61ae00001999a",
          "sha256": "16225b85acfcdf70eb7686915f8719df0adb92cb1f6823251fe6308bb8d17782",
          "sha1": "6c8eaa1afe6142aace9fa3350f3fa950440fb944",
          "md5": "1bcff379cc910ec9d4a66dc509203c95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v150.jar",
          "url": "natives-freetype-desktop-v150.jar",
          "size": 1098026,
          "sha512": "e6ac6bcf92703c4b49f6c993e25bbcce787b42d657a2797342e7795a6d1be4aabdc710314ad968a252995a449a69fb935be38af2a9d39c0623f61ae00001999a",
          "sha256": "16225b85acfcdf70eb7686915f8719df0adb92cb1f6823251fe6308bb8d17782",
          "sha1": "6c8eaa1afe6142aace9fa3350f3fa950440fb944",
          "md5": "1bcff379cc910ec9d4a66dc509203c95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v150-sources.jar",
          "url": "natives-freetype-desktop-v150-sources.jar",
          "size": 1098026,
          "sha512": "307226bd0f97e90edc016c09d95e5debe45c2dae099ef676bd2c5b817a4e1d0c2308a03dc40e13e79b3ba8b6c562a177c8017bf493838982920acd9a2cc5c518",
          "sha256": "878261a67d232eb7ff03476b5b1217de91b6cf9ec21c82b7d17af70421bf9522",
          "sha1": "06fd1018ff5668d4e1aba36983adee395c58a872",
          "md5": "29bbe40e8c5f4f9e93f809e57d90a989"
        }
      ]
    }
  ]
}
