{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "tiled",
    "version": "v149",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiled-v149.jar",
          "url": "tiled-v149.jar",
          "size": 42985,
          "sha512": "ccbecd80d9703106c7602ce95b172b1377c04f05aad486f2d42ff125d854838aed505792ddf6264cfb17049240a1a449593221356c32c3def24edaace829555a",
          "sha256": "d89abac9dac9c19df35f2355d1ed362df5066d0338d77a153986da4a0a7e83e5",
          "sha1": "a88b1eab5c13a643a45ceb0a7b345cdce4d82623",
          "md5": "e4ea5708e6b6e69aad7ed7867a258fd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v149.jar",
          "url": "tiled-v149.jar",
          "size": 42985,
          "sha512": "ccbecd80d9703106c7602ce95b172b1377c04f05aad486f2d42ff125d854838aed505792ddf6264cfb17049240a1a449593221356c32c3def24edaace829555a",
          "sha256": "d89abac9dac9c19df35f2355d1ed362df5066d0338d77a153986da4a0a7e83e5",
          "sha1": "a88b1eab5c13a643a45ceb0a7b345cdce4d82623",
          "md5": "e4ea5708e6b6e69aad7ed7867a258fd9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v149-sources.jar",
          "url": "tiled-v149-sources.jar",
          "size": 23367,
          "sha512": "a8169b289710f8257787e142e4deb52c43d9c2312946640c9c28e650cdd4a0bb4d40000eae92ab01a15bcf9ea5b3b2329c9d7967a2e68fee179148be851b2cec",
          "sha256": "ca763a9fc9c8c8f1995b09a36584646aca7c56dce906aff59474c6426606f734",
          "sha1": "86ce2436e400a48fa40547e438534cfa5e2de35f",
          "md5": "ec784e87d5c178d74f6fb242f42e004f"
        }
      ]
    }
  ]
}
