{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "tiled",
    "version": "v152.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiled-v152.2.jar",
          "url": "tiled-v152.2.jar",
          "size": 42985,
          "sha512": "4bda7a7bac3121a5ff87c712268ef54f5310f0658f090b743e3a35644333e99b5fdd76ed3328a70251be47a8920def3b17c14418215377a86c13f1211d80b06a",
          "sha256": "3f35137b03ceecd99f32e07bd6ebdb7f5a478235d4fae1cc4c16f25f4160360e",
          "sha1": "127b56a77551b2c6cb4c4774589a99ef66c0467f",
          "md5": "62da5d278947b53b975a36aab8f1bd57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v152.2.jar",
          "url": "tiled-v152.2.jar",
          "size": 42985,
          "sha512": "4bda7a7bac3121a5ff87c712268ef54f5310f0658f090b743e3a35644333e99b5fdd76ed3328a70251be47a8920def3b17c14418215377a86c13f1211d80b06a",
          "sha256": "3f35137b03ceecd99f32e07bd6ebdb7f5a478235d4fae1cc4c16f25f4160360e",
          "sha1": "127b56a77551b2c6cb4c4774589a99ef66c0467f",
          "md5": "62da5d278947b53b975a36aab8f1bd57"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v152.2-sources.jar",
          "url": "tiled-v152.2-sources.jar",
          "size": 23367,
          "sha512": "f4568d13085599f6ca2e19df87b6b76058ad4dcd91ef537c76424fbdaa6d327c2a933f865a94ec753b728895b84cf490780856785f21e8cd1866daf8ac56d99d",
          "sha256": "6c9939bae303c9143cc5e8268bcae78b07ed730a764ea1d0e50ecfc4479a5a2a",
          "sha1": "43251c749ff0ea0c1ea97eeace5a7676b94b52e2",
          "md5": "38e23d52bf4bc868cb218051c0ef3aeb"
        }
      ]
    }
  ]
}
