{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v151",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v151.jar",
          "url": "natives-freetype-desktop-v151.jar",
          "size": 1098026,
          "sha512": "7592b678abafe18fb0f6ec8d9bea996c1a67c597455dc41c524cd8942656cb66b090c370a8e0c55337854f15aff4f7270842a0ee93819929fce7cd0b05189e54",
          "sha256": "8cc673c118a1e554433994c9625af266552e6ed4c3b6f049893d5d9da25024f6",
          "sha1": "f32e9d2a391fa770d74d87ff5be6dc038934237f",
          "md5": "721a95978fabba9fd8822eb27bab3cdc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v151.jar",
          "url": "natives-freetype-desktop-v151.jar",
          "size": 1098026,
          "sha512": "7592b678abafe18fb0f6ec8d9bea996c1a67c597455dc41c524cd8942656cb66b090c370a8e0c55337854f15aff4f7270842a0ee93819929fce7cd0b05189e54",
          "sha256": "8cc673c118a1e554433994c9625af266552e6ed4c3b6f049893d5d9da25024f6",
          "sha1": "f32e9d2a391fa770d74d87ff5be6dc038934237f",
          "md5": "721a95978fabba9fd8822eb27bab3cdc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v151-sources.jar",
          "url": "natives-freetype-desktop-v151-sources.jar",
          "size": 1098026,
          "sha512": "3af35c53b22a1f52781c47a3a3a5dc323c1fd5a1c484a459e27535da333797d2be589f8b5ee8f30a222206a1bed228c10eee140ff52de6a1514d63aa3d6bb3bb",
          "sha256": "5751f5cc7cc30f60f75d1b01a5c39a5ed2b8d977f4724693eea11f9217f77d88",
          "sha1": "77841022ca105dd96ed47f0ed7985f91af5adb5c",
          "md5": "15b09c876b6fd7b11e2823b6409992b3"
        }
      ]
    }
  ]
}
