{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "tiled",
    "version": "v155",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiled-v155.jar",
          "url": "tiled-v155.jar",
          "size": 42985,
          "sha512": "aab4ee86fea9cacbfe54d9651474bab4b5396f197b36c3f6e94b753aa75810903a98e160c08c7e8a10a71e1e07bc0f65ea60e9eab709e8b75a985781363e5862",
          "sha256": "71526a0c98a1c6793c1781f2cf3de108f7a3979d48aefdaed0f7e887189af26f",
          "sha1": "2e5ba24773dcbd949f78001dc477fbe55ddb4072",
          "md5": "4c0079c40b40403765a1c6aef2039398"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v155.jar",
          "url": "tiled-v155.jar",
          "size": 42985,
          "sha512": "aab4ee86fea9cacbfe54d9651474bab4b5396f197b36c3f6e94b753aa75810903a98e160c08c7e8a10a71e1e07bc0f65ea60e9eab709e8b75a985781363e5862",
          "sha256": "71526a0c98a1c6793c1781f2cf3de108f7a3979d48aefdaed0f7e887189af26f",
          "sha1": "2e5ba24773dcbd949f78001dc477fbe55ddb4072",
          "md5": "4c0079c40b40403765a1c6aef2039398"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v155-sources.jar",
          "url": "tiled-v155-sources.jar",
          "size": 23367,
          "sha512": "dbb971715a57f59dd1a4519414b852f913f31db9e572f544b533a225b2e8b120864c61ab9c1b2b53149b440a940a3abe56a29d28b69b78b21ad074016c7294ad",
          "sha256": "2f8f1f9e2a892070aa2b2fcea5f6851747a292e8a8443f85646a4a959e17d4ac",
          "sha1": "f9ca09769a074b3bdfb617745ff78ecd977c2659",
          "md5": "8359317790f46e7388b410fcb429af9d"
        }
      ]
    }
  ]
}
