{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v155.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.2.jar",
          "url": "natives-freetype-desktop-v155.2.jar",
          "size": 1098026,
          "sha512": "19505fd6e93bf1749d1abf13b8a5d68a8e2b04682c425da321a48170815f13dc7a2897ebe18d19db2856e7e2c7978dc77ba202859cf18268c24b8b93f10ee79b",
          "sha256": "a2b2c34bad7ad623559dd30fd180a1fdd9c0e1775f77517d2a040119849e2f0b",
          "sha1": "a46812dd9cea14fc71e20749b044dae11a3c082e",
          "md5": "32727bb2cbcbe7afc328da739c6745ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.2.jar",
          "url": "natives-freetype-desktop-v155.2.jar",
          "size": 1098026,
          "sha512": "19505fd6e93bf1749d1abf13b8a5d68a8e2b04682c425da321a48170815f13dc7a2897ebe18d19db2856e7e2c7978dc77ba202859cf18268c24b8b93f10ee79b",
          "sha256": "a2b2c34bad7ad623559dd30fd180a1fdd9c0e1775f77517d2a040119849e2f0b",
          "sha1": "a46812dd9cea14fc71e20749b044dae11a3c082e",
          "md5": "32727bb2cbcbe7afc328da739c6745ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.2-sources.jar",
          "url": "natives-freetype-desktop-v155.2-sources.jar",
          "size": 1098026,
          "sha512": "fd059f1e9482a46c5e062110b22c7fe37f539792e3c20e86b4022f564ba8cd3e0e11fed9cad5a9b71ce57045794e2c0dd5bd4391da2991f887f9019f96f059b8",
          "sha256": "e1b53f1ac0362d6f94f731a117cd6e03405237767424f89e2cd60cb57a29ea5b",
          "sha1": "141a117318c158030f69f5e01be96c368512713d",
          "md5": "d33246bfb16a4510df027feac8f0abfb"
        }
      ]
    }
  ]
}
