{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-ios",
    "version": "v155.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v155.3.jar",
          "url": "natives-box2d-ios-v155.3.jar",
          "size": 2384392,
          "sha512": "b841f85e50125d8402cbbf7864f8480e4984655af33c1fd2d0b444a1f508e6ae336b9d9269c646691aa5859a2b785cf6fc7b53205a7423db28fc5ec82d036fad",
          "sha256": "844d45b10d79dbae2123144989e2271a4b56d75d1f2c612a093452001f5cceac",
          "sha1": "b17e51326155da12bde061596dedb17d4f13a5eb",
          "md5": "34fbdef9f8dc74bc131938776fb6da04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v155.3.jar",
          "url": "natives-box2d-ios-v155.3.jar",
          "size": 2384392,
          "sha512": "b841f85e50125d8402cbbf7864f8480e4984655af33c1fd2d0b444a1f508e6ae336b9d9269c646691aa5859a2b785cf6fc7b53205a7423db28fc5ec82d036fad",
          "sha256": "844d45b10d79dbae2123144989e2271a4b56d75d1f2c612a093452001f5cceac",
          "sha1": "b17e51326155da12bde061596dedb17d4f13a5eb",
          "md5": "34fbdef9f8dc74bc131938776fb6da04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v155.3-sources.jar",
          "url": "natives-box2d-ios-v155.3-sources.jar",
          "size": 2384392,
          "sha512": "b625c1af8fb20ba32b7c5f4d45eef4a97333f73441955eb45e576d03e71c4111f5acc43f24d057f592a8d04123204e6475eb4310c580072255215ecc40a4a69f",
          "sha256": "2ef45155355579fe4d109471d37c6301f5d80f27033f6e94986f895dd94c4850",
          "sha1": "0af6af631b2bbb196d80e58dbbd623ff375e91e3",
          "md5": "1045068350824d5872e72b2126f0034d"
        }
      ]
    }
  ]
}
