{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-desktop",
    "version": "v154",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v154.jar",
          "url": "natives-box2d-desktop-v154.jar",
          "size": 512159,
          "sha512": "79c0350c762a537c9d4d36de4e104685748bfb1036f307d3622ec0bf050753118c6f7400fa65776ecd892828a02b494ab09fb715062338499e862fc4bef56bb0",
          "sha256": "ba3b4d3f740e12f585fd24755e50b779eff67959dbfe2727e79e2b9f48de87e1",
          "sha1": "dda52460d9654a010699ad6a7f54e0602c93cc4e",
          "md5": "f9543e253b96db75a08503ae2c15b724"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v154.jar",
          "url": "natives-box2d-desktop-v154.jar",
          "size": 512159,
          "sha512": "79c0350c762a537c9d4d36de4e104685748bfb1036f307d3622ec0bf050753118c6f7400fa65776ecd892828a02b494ab09fb715062338499e862fc4bef56bb0",
          "sha256": "ba3b4d3f740e12f585fd24755e50b779eff67959dbfe2727e79e2b9f48de87e1",
          "sha1": "dda52460d9654a010699ad6a7f54e0602c93cc4e",
          "md5": "f9543e253b96db75a08503ae2c15b724"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v154-sources.jar",
          "url": "natives-box2d-desktop-v154-sources.jar",
          "size": 512159,
          "sha512": "3204d358da11e42e73a248adcf825a5777284b39bda8581adbd146f63c54dae66281ad3c80cbbe7cc43d65cbc83f5a7f5e1d3dcdce0388a6e63b100ec5c0644a",
          "sha256": "76bf782a06739d5c356cc8733e83fa96e16b346f5518878fd03d39f51f6b5dd3",
          "sha1": "c5c18210f76e04f1c172681acf7b5e486eca9be1",
          "md5": "b74652f86df93feb42dc8d5e1540d2dd"
        }
      ]
    }
  ]
}
