{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "arcnet",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "arcnet-v156.1.jar",
          "url": "arcnet-v156.1.jar",
          "size": 51138,
          "sha512": "36c687448b8722e13f2a8c55aa017422af600334e86f1ea054489d177a27a14f94c6a9c538c77d22f1aa60d945266b9df1fc576e2e544d17aa338b177b14ae07",
          "sha256": "d31e3b7d0b20a4e85b36a91a3a2627e5002a840bc4b79de15f8e2df023aa5d02",
          "sha1": "e5ddf3e014dbb9e1b17c670338c8dda6f4fbaf20",
          "md5": "baf33f238949226b97e7d9f2d939a4b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arcnet-v156.1.jar",
          "url": "arcnet-v156.1.jar",
          "size": 51138,
          "sha512": "36c687448b8722e13f2a8c55aa017422af600334e86f1ea054489d177a27a14f94c6a9c538c77d22f1aa60d945266b9df1fc576e2e544d17aa338b177b14ae07",
          "sha256": "d31e3b7d0b20a4e85b36a91a3a2627e5002a840bc4b79de15f8e2df023aa5d02",
          "sha1": "e5ddf3e014dbb9e1b17c670338c8dda6f4fbaf20",
          "md5": "baf33f238949226b97e7d9f2d939a4b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arcnet-v156.1-sources.jar",
          "url": "arcnet-v156.1-sources.jar",
          "size": 27800,
          "sha512": "23dafe3ea264df66e57d28a9e4278d96e978ed3b0967f54234fc48e577ff5de92feef3089b0d876ef5f7aabdd0aec784da36dacc7e479b3609a0b163534f318a",
          "sha256": "f25bf7c4a66f8e7ffc06e6c42d05c89a92a14386718d9ccc6869065c0530bd67",
          "sha1": "57fe44b44304cf142951dd95d39bad91a80850a3",
          "md5": "98184ab5f5f2458cb172d70fc9c360cc"
        }
      ]
    }
  ]
}
