{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v154.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v154.3.jar",
          "url": "natives-freetype-desktop-v154.3.jar",
          "size": 1098026,
          "sha512": "6ab51b236e69563023e613150e81c1b79a777f19984c008c1f6d595865d3d332bb285b9d091f7b2baeeb13d78c51057050ea5e6d6bb5d6646ce641a014b8a1ba",
          "sha256": "7da2aedc191dbac0e05934013498056ba79e10d6641fa38c208292cb277c59b8",
          "sha1": "278b64c45018f8dfb8594ac06e6ed9227efde288",
          "md5": "39112f2d781cd9ba8ed3e2229df1a35e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v154.3.jar",
          "url": "natives-freetype-desktop-v154.3.jar",
          "size": 1098026,
          "sha512": "6ab51b236e69563023e613150e81c1b79a777f19984c008c1f6d595865d3d332bb285b9d091f7b2baeeb13d78c51057050ea5e6d6bb5d6646ce641a014b8a1ba",
          "sha256": "7da2aedc191dbac0e05934013498056ba79e10d6641fa38c208292cb277c59b8",
          "sha1": "278b64c45018f8dfb8594ac06e6ed9227efde288",
          "md5": "39112f2d781cd9ba8ed3e2229df1a35e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v154.3-sources.jar",
          "url": "natives-freetype-desktop-v154.3-sources.jar",
          "size": 1098026,
          "sha512": "d280efb99fcaf44583b9b6dcd31523a5f16f29fc2a09b08cf5d2749172bf0356f81f6a2e368b82e732764c75f594607f07ba3f4003358c4b7f40f17dd4353364",
          "sha256": "bbc19b61102342e323528d255d1d33d8d93881bbb9506f59e64d6d79e1de589c",
          "sha1": "68ef0c696fce965374b596231d897cd48fc4c463",
          "md5": "357c88326e6fabc63b33e9dc0aecd70e"
        }
      ]
    }
  ]
}
