{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v150.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v150.1.jar",
          "url": "backend-sdl-v150.1.jar",
          "size": 3812181,
          "sha512": "18c8003d811bea9ef4933f15252c0461723f5ea74a21718c8abf4eefba5e1dba536112bbf266d04955225653e29c969c4eabb267b5de15ea0ae1bc84c76378ab",
          "sha256": "ca7d50f5beabce1442b23bb7d3ac6faf48668669f3b1f7d6379ca735a0a4de05",
          "sha1": "33379e0356ebf148b9e6148753c6655981c0b8b8",
          "md5": "5821dbc8948e9db5e4b83af9c7bcb276"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v150.1.jar",
          "url": "backend-sdl-v150.1.jar",
          "size": 3812181,
          "sha512": "18c8003d811bea9ef4933f15252c0461723f5ea74a21718c8abf4eefba5e1dba536112bbf266d04955225653e29c969c4eabb267b5de15ea0ae1bc84c76378ab",
          "sha256": "ca7d50f5beabce1442b23bb7d3ac6faf48668669f3b1f7d6379ca735a0a4de05",
          "sha1": "33379e0356ebf148b9e6148753c6655981c0b8b8",
          "md5": "5821dbc8948e9db5e4b83af9c7bcb276"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v150.1-sources.jar",
          "url": "backend-sdl-v150.1-sources.jar",
          "size": 3793108,
          "sha512": "8fd4f8c6c094964e016fde6eec6b7ee8688a3251ee58eafca5c222461de2bcbc6a7e94b14869b444662f7bee4ddec6564e038bbf36e1dbb4ad1e245c03b98d6b",
          "sha256": "5c4a5468d230627c0933b77e90c23749b96a30cdfb0405ebbcbf68ade652323d",
          "sha1": "65385ca360d5bb94559485033672f65eb6b2061b",
          "md5": "47e2919ee429a62ddbf23b7bea6759c4"
        }
      ]
    }
  ]
}
