{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v156.1.jar",
          "url": "natives-freetype-desktop-v156.1.jar",
          "size": 900078,
          "sha512": "3ce84eb7e53075560a19ece56cf7c9e1e7a185a067d086c40f15836d556468a8da41097462bad1e1dc0807eee57d52a113c21f58d38f85ad0793c7a0332f325d",
          "sha256": "bde83ddca02f1812dadfebc9321119fca2c32c57d842996e0a277ee037d7765c",
          "sha1": "6ce82142c2b927e7490ed78accecd4cde1d16f76",
          "md5": "8af005521b1f06d910afca087a2a9e1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v156.1.jar",
          "url": "natives-freetype-desktop-v156.1.jar",
          "size": 900078,
          "sha512": "3ce84eb7e53075560a19ece56cf7c9e1e7a185a067d086c40f15836d556468a8da41097462bad1e1dc0807eee57d52a113c21f58d38f85ad0793c7a0332f325d",
          "sha256": "bde83ddca02f1812dadfebc9321119fca2c32c57d842996e0a277ee037d7765c",
          "sha1": "6ce82142c2b927e7490ed78accecd4cde1d16f76",
          "md5": "8af005521b1f06d910afca087a2a9e1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v156.1-sources.jar",
          "url": "natives-freetype-desktop-v156.1-sources.jar",
          "size": 900078,
          "sha512": "281840cdf72e6980cc27b4b9761420d90d614344c24300271c073f3ddd3c478e0b1558ed4c24485cfbce56508f2939fe8fa4b23b5c224d578192a8876c0eaa87",
          "sha256": "413c6ea87a4ef56b52f6b65d574ee27e5d9afa789f147555a6c702da6d143028",
          "sha1": "ff60a3be4cd80ec1b361f6fb3dd8a7729bdfd35e",
          "md5": "10201594033ef9831a0abbb78db77408"
        }
      ]
    }
  ]
}
