{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "discord",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "discord-v156.1.jar",
          "url": "discord-v156.1.jar",
          "size": 15281,
          "sha512": "196ea66467f598cf6c66d6bc1ff99b0ec15f9e6ab35f1c0e6531aa43d132dce9e3c8aaf911ee8ab107da683bd15058ee958564f9943f26904791e1fe0213eff3",
          "sha256": "9ae4da79c9686c146ce426747976e9544d60221d84fb62a49f1dd964ee36c37b",
          "sha1": "73826d56ae64b07ad879252ed5135e2ce7023fd7",
          "md5": "2db4bfe50279eed89ded29a364fe9c3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-v156.1.jar",
          "url": "discord-v156.1.jar",
          "size": 15281,
          "sha512": "196ea66467f598cf6c66d6bc1ff99b0ec15f9e6ab35f1c0e6531aa43d132dce9e3c8aaf911ee8ab107da683bd15058ee958564f9943f26904791e1fe0213eff3",
          "sha256": "9ae4da79c9686c146ce426747976e9544d60221d84fb62a49f1dd964ee36c37b",
          "sha1": "73826d56ae64b07ad879252ed5135e2ce7023fd7",
          "md5": "2db4bfe50279eed89ded29a364fe9c3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-v156.1-sources.jar",
          "url": "discord-v156.1-sources.jar",
          "size": 4426,
          "sha512": "60887107e40e059ca42634c7391b0086302a7c2ed477e66e55d9b333776d5be99d9bc920d6dd007d4efc060ed38142e12be15f6532d6b4b8cd13dd234c36741c",
          "sha256": "49bd516dcb151532c2c8b021305b2754f798f2f628104165b4358af80cff404d",
          "sha1": "271c5ece7fad1f3130fceee03c7da57fc8d97ec4",
          "md5": "9b8bd5456d54b6d530c990228207eab4"
        }
      ]
    }
  ]
}
