{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-android",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-android-v156.1.jar",
          "url": "backend-android-v156.1.jar",
          "size": 69667,
          "sha512": "9fbf13f76fc16373bfb93b2527e68e3302761c104434d48799d2871e7c669442ccdf8f853fc3c0bb77ede8e32b74972d2d73800babc69cd7594641a3b05841d3",
          "sha256": "0d74824e200534211884210a16aa06d84e8d1ff3340d5c815142bfc722a67197",
          "sha1": "19d4e86d6a437dc128f89711e1dcb79e051cf093",
          "md5": "db47e653772704fc73c69d580a576dbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-android-v156.1.jar",
          "url": "backend-android-v156.1.jar",
          "size": 69667,
          "sha512": "9fbf13f76fc16373bfb93b2527e68e3302761c104434d48799d2871e7c669442ccdf8f853fc3c0bb77ede8e32b74972d2d73800babc69cd7594641a3b05841d3",
          "sha256": "0d74824e200534211884210a16aa06d84e8d1ff3340d5c815142bfc722a67197",
          "sha1": "19d4e86d6a437dc128f89711e1dcb79e051cf093",
          "md5": "db47e653772704fc73c69d580a576dbc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-android-v156.1-sources.jar",
          "url": "backend-android-v156.1-sources.jar",
          "size": 36704,
          "sha512": "18ef76e01735c7fb07b14dc20eeca9b7ff1cc9eeeadcdb3e3889cd434e9eddd739de236f9570230f176b4157de09ccbc0c562147472aaf84da6abb95bff47847",
          "sha256": "5a20b6281a87d58ff61302ccc1d9fc06482f755f5210bb4ee863cf10193037f6",
          "sha1": "041934c9725ff21119eed3d97770b63e8caadbb3",
          "md5": "cda876d90c6bc33f62076526da22abf6"
        }
      ]
    }
  ]
}
