{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "box2d",
    "version": "v155",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "box2d-v155.jar",
          "url": "box2d-v155.jar",
          "size": 58093,
          "sha512": "b12866499049d2f4916fae9ef40f153a29b152720d12c08cdedb7e8711afafa5452122177323b8cae9e32a397fa99a99f913bf0db74a7f918f4439298675de9e",
          "sha256": "02ca636c9e6d7c4fc6d6963937871423b3c2b5692b84b2965c11ce021d491204",
          "sha1": "60186eb7cd0b068ec3bc7b401bbde6e7f6dd1fd8",
          "md5": "17a552a96857237927553759bace8714"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box2d-v155.jar",
          "url": "box2d-v155.jar",
          "size": 58093,
          "sha512": "b12866499049d2f4916fae9ef40f153a29b152720d12c08cdedb7e8711afafa5452122177323b8cae9e32a397fa99a99f913bf0db74a7f918f4439298675de9e",
          "sha256": "02ca636c9e6d7c4fc6d6963937871423b3c2b5692b84b2965c11ce021d491204",
          "sha1": "60186eb7cd0b068ec3bc7b401bbde6e7f6dd1fd8",
          "md5": "17a552a96857237927553759bace8714"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box2d-v155-sources.jar",
          "url": "box2d-v155-sources.jar",
          "size": 52592,
          "sha512": "4d202bf77f950a8165cab980eaf8604340a60798303beebdb503dc59f56596b2bf3e07be30871185cec27fd14237d2fa2cf33ae0191b8166e2c78323a26d16f8",
          "sha256": "e40385ad5e384e0c5e91e0d5ccd223d4c2481d44f95188f0210f3ad4ea198fbf",
          "sha1": "d0a841eefadb7fbf2c0d362f34729366f736256e",
          "md5": "428e3649eba92f9d600eeba7f53be31d"
        }
      ]
    }
  ]
}
