{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-desktop",
    "version": "v155.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v155.2.jar",
          "url": "natives-box2d-desktop-v155.2.jar",
          "size": 512159,
          "sha512": "36266a2b003309eeb300fa5c649c088ce40ead03a1768e5ff71c14ff4ccb67f68ab201d2f5d45461d5e7d511a23cf50cc8967dd3822f0b3d02ac48f8b8a97e46",
          "sha256": "4ba91e8709291cee2cade99ebcdf90c28623cbb4da68edd69d3a4498bb99d17d",
          "sha1": "93ba473ebcb6b978b31d8628e1a6e823a7fd430d",
          "md5": "190c3da72917b3618d818573489bea45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v155.2.jar",
          "url": "natives-box2d-desktop-v155.2.jar",
          "size": 512159,
          "sha512": "36266a2b003309eeb300fa5c649c088ce40ead03a1768e5ff71c14ff4ccb67f68ab201d2f5d45461d5e7d511a23cf50cc8967dd3822f0b3d02ac48f8b8a97e46",
          "sha256": "4ba91e8709291cee2cade99ebcdf90c28623cbb4da68edd69d3a4498bb99d17d",
          "sha1": "93ba473ebcb6b978b31d8628e1a6e823a7fd430d",
          "md5": "190c3da72917b3618d818573489bea45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v155.2-sources.jar",
          "url": "natives-box2d-desktop-v155.2-sources.jar",
          "size": 512159,
          "sha512": "bb2788fc3351b8551611b4a69678d7204d9770284c0a203fc0af796bcd3b32e455e55a4b70078f09bbf584637429d5fdaafb51e89b2b670b5b96e5b289bb3f9a",
          "sha256": "c42e81ac654800e0d146b8dbb0c344cbf690b8db6b6a0059121a9360a0c7506c",
          "sha1": "e343ecd48ea88a5d78c8c052d7f4fc7112e0c557",
          "md5": "e1886dcf8d3651de2e51bed1bb74f142"
        }
      ]
    }
  ]
}
