{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-ios",
    "version": "v155.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v155.1.jar",
          "url": "natives-box2d-ios-v155.1.jar",
          "size": 2384392,
          "sha512": "6d577ac3b51e6ea77dff1a95dee76ce07221fc5bf51ae300dc8e8c11460373c3939d97899d6c00fc37807c060a801677aa13cb1166949762a1937b2b63086037",
          "sha256": "6ea2f6ab1d99b5001796ba81fb18251de8c6f6e150d708522fd2000f5a516823",
          "sha1": "b54b64729deeedf113825fe6a7c1b91a19bb6fd2",
          "md5": "08635d530e0b2df21122ad66a3c4771b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v155.1.jar",
          "url": "natives-box2d-ios-v155.1.jar",
          "size": 2384392,
          "sha512": "6d577ac3b51e6ea77dff1a95dee76ce07221fc5bf51ae300dc8e8c11460373c3939d97899d6c00fc37807c060a801677aa13cb1166949762a1937b2b63086037",
          "sha256": "6ea2f6ab1d99b5001796ba81fb18251de8c6f6e150d708522fd2000f5a516823",
          "sha1": "b54b64729deeedf113825fe6a7c1b91a19bb6fd2",
          "md5": "08635d530e0b2df21122ad66a3c4771b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v155.1-sources.jar",
          "url": "natives-box2d-ios-v155.1-sources.jar",
          "size": 2384392,
          "sha512": "a314c0e4d67a591a6e2e3d0ca46bd7714749b271c405803de46f333438251b4361d8903fbe80761543a46f0090ed70e975c3b9c4c15c6a26d983670efb0f0c7a",
          "sha256": "e0b864de0a8593fde19541995699c6605a157c3f48a77028b718dc2c7dc18f88",
          "sha1": "2eb3eaae4a28eb0d9440e8e759f7e298473f1b22",
          "md5": "4c8f7cc3b9b9a6cf721cceacbab5911c"
        }
      ]
    }
  ]
}
