{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v155.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v155.3.jar",
          "url": "backends-v155.3.jar",
          "size": 261,
          "sha512": "2f83b7dbe4e8a6665c18715cb7be39e9a620498189b97a0504bda43a24159f7ad6773e4586898f7d46a962322f5411bdcf570fb9c27f4d8c5197aea50fb9f289",
          "sha256": "f3bdb4b3114141160e260d6f40860d5adb627ce0c22ad7fdb947c8f853f7bd7d",
          "sha1": "2d7c2348b27681d779e6c37b5f664208751900b9",
          "md5": "66ad5d76396dfd06a4981a96b4cabf25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v155.3.jar",
          "url": "backends-v155.3.jar",
          "size": 261,
          "sha512": "2f83b7dbe4e8a6665c18715cb7be39e9a620498189b97a0504bda43a24159f7ad6773e4586898f7d46a962322f5411bdcf570fb9c27f4d8c5197aea50fb9f289",
          "sha256": "f3bdb4b3114141160e260d6f40860d5adb627ce0c22ad7fdb947c8f853f7bd7d",
          "sha1": "2d7c2348b27681d779e6c37b5f664208751900b9",
          "md5": "66ad5d76396dfd06a4981a96b4cabf25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v155.3-sources.jar",
          "url": "backends-v155.3-sources.jar",
          "size": 261,
          "sha512": "2f83b7dbe4e8a6665c18715cb7be39e9a620498189b97a0504bda43a24159f7ad6773e4586898f7d46a962322f5411bdcf570fb9c27f4d8c5197aea50fb9f289",
          "sha256": "f3bdb4b3114141160e260d6f40860d5adb627ce0c22ad7fdb947c8f853f7bd7d",
          "sha1": "2d7c2348b27681d779e6c37b5f664208751900b9",
          "md5": "66ad5d76396dfd06a4981a96b4cabf25"
        }
      ]
    }
  ]
}
