{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v150.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v150.1.jar",
          "url": "natives-freetype-desktop-v150.1.jar",
          "size": 1098026,
          "sha512": "5c76eb4b112c9518b63a6e0e3815c09ebc0b59e5e1af414d0ad15fc604c5cc7253b1ccdffbce1dbc252e3857e8b31ec4286937d5e082bdf1ed7512fd3e7987f4",
          "sha256": "b5f7b720940c1ed7c42b7675a4bea2c748f8c6d4c7f875420774878a4396e621",
          "sha1": "66a4bf84b5941494e3189b26c361c12976a2629c",
          "md5": "5b657cb150ee5b620891f3d6c0ea204d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v150.1.jar",
          "url": "natives-freetype-desktop-v150.1.jar",
          "size": 1098026,
          "sha512": "5c76eb4b112c9518b63a6e0e3815c09ebc0b59e5e1af414d0ad15fc604c5cc7253b1ccdffbce1dbc252e3857e8b31ec4286937d5e082bdf1ed7512fd3e7987f4",
          "sha256": "b5f7b720940c1ed7c42b7675a4bea2c748f8c6d4c7f875420774878a4396e621",
          "sha1": "66a4bf84b5941494e3189b26c361c12976a2629c",
          "md5": "5b657cb150ee5b620891f3d6c0ea204d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v150.1-sources.jar",
          "url": "natives-freetype-desktop-v150.1-sources.jar",
          "size": 1098026,
          "sha512": "a848d4f5e4e113063d1a48045a4b58531dbb5747223465a1c1c682f9baf89a38cc6faca4cc9cd0e7706c0deb10e75f3c16ba9904437c897acc8492a15ec46651",
          "sha256": "c59501080d940df163ec58f1439985b8ad209fdcf00909d3dba8071ac92e9175",
          "sha1": "e0c9b8ff648634e32e3979c5a90f9984af1f58e6",
          "md5": "5a2f4fec24358f75f5a4dfe21f1ceacd"
        }
      ]
    }
  ]
}
