{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-filedialogs",
    "version": "v155.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-filedialogs-v155.1.jar",
          "url": "natives-filedialogs-v155.1.jar",
          "size": 117137,
          "sha512": "8d7486b96fdd64222756fcbc2cd2de91f95017840077d97ccb57f1dac739842018c07803c780eeb869733d4bc711742b55dec9fb1cb81b950e830e970600cb30",
          "sha256": "c1c83cb4df78fdf260aac3d574b91f7cbb9d2592e0179d822257c53356e2e438",
          "sha1": "4d898d4fd1992b25c3a24273896b6349391a84ff",
          "md5": "014b8729497ebefe81af1191040c88a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-filedialogs-v155.1.jar",
          "url": "natives-filedialogs-v155.1.jar",
          "size": 117137,
          "sha512": "8d7486b96fdd64222756fcbc2cd2de91f95017840077d97ccb57f1dac739842018c07803c780eeb869733d4bc711742b55dec9fb1cb81b950e830e970600cb30",
          "sha256": "c1c83cb4df78fdf260aac3d574b91f7cbb9d2592e0179d822257c53356e2e438",
          "sha1": "4d898d4fd1992b25c3a24273896b6349391a84ff",
          "md5": "014b8729497ebefe81af1191040c88a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-filedialogs-v155.1-sources.jar",
          "url": "natives-filedialogs-v155.1-sources.jar",
          "size": 117137,
          "sha512": "30db4ae513303265d0b60c1cba0d6ba10c8fd1523d1d8e03b784fcde7ced14afcba54a149913b509df470aca6f96c54d91db9e2cd1a7df930395212336a50148",
          "sha256": "7d87c4049fe3ac73364eeaa835d91e978bea3a6e0b1ea180778654a16d9e642e",
          "sha1": "092bca80b4f808b645e9f68c575a50f5000071be",
          "md5": "9ebfad37e1cd6ffc90668e22b5e1b7a4"
        }
      ]
    }
  ]
}
