{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v155.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.1.jar",
          "url": "natives-freetype-desktop-v155.1.jar",
          "size": 1098026,
          "sha512": "57b079c99d6b2c167d6ce4e4d24555ee1fd817ad82b803e3cf92f0354aea96db99ec0e16fbdfe89c913b88914697c6b04663d6192263d2ef10582eac04a81d8f",
          "sha256": "84aab2efae42c851453122b4f77f6c91a9e173c61f18def34f23c3a51badf316",
          "sha1": "878b886279c4c84c7bb95e2f9a45abcf9af12b89",
          "md5": "050c74fadf18da0c531420182fcfed90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.1.jar",
          "url": "natives-freetype-desktop-v155.1.jar",
          "size": 1098026,
          "sha512": "57b079c99d6b2c167d6ce4e4d24555ee1fd817ad82b803e3cf92f0354aea96db99ec0e16fbdfe89c913b88914697c6b04663d6192263d2ef10582eac04a81d8f",
          "sha256": "84aab2efae42c851453122b4f77f6c91a9e173c61f18def34f23c3a51badf316",
          "sha1": "878b886279c4c84c7bb95e2f9a45abcf9af12b89",
          "md5": "050c74fadf18da0c531420182fcfed90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.1-sources.jar",
          "url": "natives-freetype-desktop-v155.1-sources.jar",
          "size": 1098026,
          "sha512": "27ef1265ff41c7c148e53f23721b2df6f4874a1fe4aa7528725645c5423c2a53f1dbfc080fff83bdf96c31fc989a2655fb776f00ab40f09ce848343f789c33cb",
          "sha256": "59b0f6c9d1cf94f84cfea46c8fe1d7149cfcd9cc303d93b779204fe306d3c2f6",
          "sha1": "13cb969b99e51d912e7f4270f3a172c848e04130",
          "md5": "3758126591746ef1e800fe29c10e84da"
        }
      ]
    }
  ]
}
