{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-ios",
    "version": "v149",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v149.jar",
          "url": "natives-box2d-ios-v149.jar",
          "size": 2384392,
          "sha512": "c514e5252affccb83aaa579abbe602defa760a9042f6cf20fd0d59bba17dfc7ecd6b2fafcbef1e432853fc3c83238a367f40d9b29745b95f67909b113da941ed",
          "sha256": "29028c3e9579dafde12ffc8fb0750b9d9358ddc9e19f910275b204756dcb5244",
          "sha1": "d5147a89cbd3675480971d442834664da8985418",
          "md5": "7fd90f657a7105eb39a879af673fbd5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v149.jar",
          "url": "natives-box2d-ios-v149.jar",
          "size": 2384392,
          "sha512": "c514e5252affccb83aaa579abbe602defa760a9042f6cf20fd0d59bba17dfc7ecd6b2fafcbef1e432853fc3c83238a367f40d9b29745b95f67909b113da941ed",
          "sha256": "29028c3e9579dafde12ffc8fb0750b9d9358ddc9e19f910275b204756dcb5244",
          "sha1": "d5147a89cbd3675480971d442834664da8985418",
          "md5": "7fd90f657a7105eb39a879af673fbd5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v149-sources.jar",
          "url": "natives-box2d-ios-v149-sources.jar",
          "size": 2384392,
          "sha512": "ec76d2a51610e07b648f2ee43ef33ace7d005cd810e88bfb11584adbf0aca0016bee5802afc586b68df245382c4d553c7fe05ab22842accb69222ac449b57218",
          "sha256": "bd566d1bf9300f4b75cae9acf66f92dcbf3e4ec0b131f44fe909ad49340c5d1d",
          "sha1": "b1eb7e5796e8dbd8fbba52fcb5e68f960f877375",
          "md5": "69e1816ffb32f46f5a4a414229d384b8"
        }
      ]
    }
  ]
}
