{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "tiled",
    "version": "v152.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiled-v152.1.jar",
          "url": "tiled-v152.1.jar",
          "size": 42985,
          "sha512": "6a4ebab1f429596ef01c4eb9cf331bf5915ca3e8514ac0c095d1d836f108da14a8afe62fe9cedbcc74d77aff171ea6caccc4c1bf44b38eed504336236a38a502",
          "sha256": "ba3cab918aea508c7e9332e188eb6121d9ae25116c601f7011ec68abf11e45b7",
          "sha1": "86b5b5022ce6c49e5425c97a511c0c17a953d92f",
          "md5": "b60bd11bd626a45610ab2fcfe0661971"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v152.1.jar",
          "url": "tiled-v152.1.jar",
          "size": 42985,
          "sha512": "6a4ebab1f429596ef01c4eb9cf331bf5915ca3e8514ac0c095d1d836f108da14a8afe62fe9cedbcc74d77aff171ea6caccc4c1bf44b38eed504336236a38a502",
          "sha256": "ba3cab918aea508c7e9332e188eb6121d9ae25116c601f7011ec68abf11e45b7",
          "sha1": "86b5b5022ce6c49e5425c97a511c0c17a953d92f",
          "md5": "b60bd11bd626a45610ab2fcfe0661971"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v152.1-sources.jar",
          "url": "tiled-v152.1-sources.jar",
          "size": 23367,
          "sha512": "5ccf66ed28a091c374686fc4d9c81d64b24e26c84d9202aa0cee66e72c0174a86172ba9db6618d0736c98cf9be92b7805e2b781ddd076360f4a52a9cf7eebdb3",
          "sha256": "3d3a5c74d26d8843273436e01e16000602967974e216737fc30b95360e2855eb",
          "sha1": "abf9f36f1dc40f6c3c8095533684efb1010ed287",
          "md5": "af7140e97db6264acca20679208eb449"
        }
      ]
    }
  ]
}
