{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v154.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v154.2.jar",
          "url": "natives-freetype-desktop-v154.2.jar",
          "size": 1098026,
          "sha512": "179e37a3a7f6978ccb64872ecf9eb69c631067ca15722ebf45c7ba970bf921aa8921875f639427866f68f8f238312cb255e1511f44816eb57dfe7755a0676518",
          "sha256": "c457a6d78bef0f8488f1b55fdf768001244a4fcffbcabd5a02b2528c88365224",
          "sha1": "0960b40dda93d75aa7fb19fa67a6d04de02ad53e",
          "md5": "403b1c9fcead70e264915d4a1b884276"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v154.2.jar",
          "url": "natives-freetype-desktop-v154.2.jar",
          "size": 1098026,
          "sha512": "179e37a3a7f6978ccb64872ecf9eb69c631067ca15722ebf45c7ba970bf921aa8921875f639427866f68f8f238312cb255e1511f44816eb57dfe7755a0676518",
          "sha256": "c457a6d78bef0f8488f1b55fdf768001244a4fcffbcabd5a02b2528c88365224",
          "sha1": "0960b40dda93d75aa7fb19fa67a6d04de02ad53e",
          "md5": "403b1c9fcead70e264915d4a1b884276"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v154.2-sources.jar",
          "url": "natives-freetype-desktop-v154.2-sources.jar",
          "size": 1098026,
          "sha512": "bd70080b49b90b1e5fadcb03d2cef6aa67f7d9efd95663949c094cd1087d93de22e85d0455a1af43117f628484668d913b8819c7efcc86fa7649df82f29d9cc0",
          "sha256": "f5f6487b747de38b0b76d48b0681a84540e31aded2d8f347a993ab942eecbeb6",
          "sha1": "766b07b1acb465286fa902d1c7e7deb4ca6f19e7",
          "md5": "dab50edafdc73a496e3901ddebd21369"
        }
      ]
    }
  ]
}
