{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "tiled",
    "version": "v155.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiled-v155.4.jar",
          "url": "tiled-v155.4.jar",
          "size": 42985,
          "sha512": "9da0b1d24ec86ccf2b594fe93fb3ca88e3b6ea1527c14da807820cb157068dbaf048ececb7a7a64966df9efa3d28275c00c94589b79c8681f73c57252816e00a",
          "sha256": "bc48da868999161c2edf41fc6488c6a54c7e590cf153b74ad9e1ccff70e6279f",
          "sha1": "d29ac709bfb977a22ec6d63e4a3a1564a5005cb8",
          "md5": "eacb2f67cde1afde6472b5059abe3ce8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v155.4.jar",
          "url": "tiled-v155.4.jar",
          "size": 42985,
          "sha512": "9da0b1d24ec86ccf2b594fe93fb3ca88e3b6ea1527c14da807820cb157068dbaf048ececb7a7a64966df9efa3d28275c00c94589b79c8681f73c57252816e00a",
          "sha256": "bc48da868999161c2edf41fc6488c6a54c7e590cf153b74ad9e1ccff70e6279f",
          "sha1": "d29ac709bfb977a22ec6d63e4a3a1564a5005cb8",
          "md5": "eacb2f67cde1afde6472b5059abe3ce8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v155.4-sources.jar",
          "url": "tiled-v155.4-sources.jar",
          "size": 23367,
          "sha512": "91c38f26c13d6d034ee63b137e0aa165da1f5f20099f1d9ea132ea1809a7e9d5a3815e2a3b20e3688512c7794c0c96a06c1c3fe1341a128e0ee21ffea3542413",
          "sha256": "b5f697c21ce6d29aa59912df9dacacf56dd3b98fc52e9ddd007a01ec7e367c4a",
          "sha1": "b62537d4066aab439be5aebdf0c9fbabd9863656",
          "md5": "1ee848e33668e4d3df052fe89bee87ae"
        }
      ]
    }
  ]
}
