{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "extensions",
    "version": "v151.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "extensions-v151.1.jar",
          "url": "extensions-v151.1.jar",
          "size": 261,
          "sha512": "d848d456df3e3b5e240e731b771cc3b71d24bcd6957b996a8b64a24bc4c73955e6145eb155bc1de5f1311adcdaeeab98277386fff52dd80f8022bea6d3d1f2a0",
          "sha256": "96bae4a8b1a156e728381c1896b318f1a9e049ca99f8b1e4dc6ef21a07ee4703",
          "sha1": "1cf163c6ec9ed3819fdf37ae5660d48cc218cbbb",
          "md5": "6f18945d1dc54b20223ca2ae3a20ef24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-v151.1.jar",
          "url": "extensions-v151.1.jar",
          "size": 261,
          "sha512": "d848d456df3e3b5e240e731b771cc3b71d24bcd6957b996a8b64a24bc4c73955e6145eb155bc1de5f1311adcdaeeab98277386fff52dd80f8022bea6d3d1f2a0",
          "sha256": "96bae4a8b1a156e728381c1896b318f1a9e049ca99f8b1e4dc6ef21a07ee4703",
          "sha1": "1cf163c6ec9ed3819fdf37ae5660d48cc218cbbb",
          "md5": "6f18945d1dc54b20223ca2ae3a20ef24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-v151.1-sources.jar",
          "url": "extensions-v151.1-sources.jar",
          "size": 261,
          "sha512": "d848d456df3e3b5e240e731b771cc3b71d24bcd6957b996a8b64a24bc4c73955e6145eb155bc1de5f1311adcdaeeab98277386fff52dd80f8022bea6d3d1f2a0",
          "sha256": "96bae4a8b1a156e728381c1896b318f1a9e049ca99f8b1e4dc6ef21a07ee4703",
          "sha1": "1cf163c6ec9ed3819fdf37ae5660d48cc218cbbb",
          "md5": "6f18945d1dc54b20223ca2ae3a20ef24"
        }
      ]
    }
  ]
}
