{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "core",
    "version": "v151",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v151.jar",
          "url": "core-v151.jar",
          "size": 5432762,
          "sha512": "95c8b911a87720423745a7a58814fd7a0e03574fc58d236cc7bf77bb12867bcd3ffe4f9c985b9463468e341fddfa0e20350da5258f124c4b8b7646da5047b00e",
          "sha256": "14d877c5f9f62f67ad3d0a46e3e918d07baf05e6930040f36e2644713f99fd47",
          "sha1": "301944eac1de34a8d5b984f49ada130613f1521a",
          "md5": "ceacc0c912d3f1edeb5300c35b2c085c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "filedialogs",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v151"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v151.jar",
          "url": "core-v151.jar",
          "size": 5432762,
          "sha512": "95c8b911a87720423745a7a58814fd7a0e03574fc58d236cc7bf77bb12867bcd3ffe4f9c985b9463468e341fddfa0e20350da5258f124c4b8b7646da5047b00e",
          "sha256": "14d877c5f9f62f67ad3d0a46e3e918d07baf05e6930040f36e2644713f99fd47",
          "sha1": "301944eac1de34a8d5b984f49ada130613f1521a",
          "md5": "ceacc0c912d3f1edeb5300c35b2c085c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v151-sources.jar",
          "url": "core-v151-sources.jar",
          "size": 1470521,
          "sha512": "e2896185cbdce5631de007ae80213b937a5f1333b68814c9fa273aa7dc599f635a5d84a096c0675663e57d2fc5a318365a30ce19346c95b711eb4e194208f06f",
          "sha256": "9d27ea2e01b40e946504af22269291645dbc69f565551812875d957ea38ef9cc",
          "sha1": "7c172df4bda342387151c2949e54f00c670188b3",
          "md5": "e063a69538b158d42aa9b92c049d6516"
        }
      ]
    }
  ]
}
