{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "tiled",
    "version": "v152",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiled-v152.jar",
          "url": "tiled-v152.jar",
          "size": 42985,
          "sha512": "774beac9d9ceac7d454c569edc49b2f3a0431bfd22dbde12eba46e87455cb1c01ace489245c28f1addde04a05abd3368cb1f7212de37194398f8079d8e7ff743",
          "sha256": "116890fc2bfc21786f805849e9badaeac3e212d689f60d93795a5512cf8b30ef",
          "sha1": "5020a957c7bf1696212afca0175969eddb4bbf7f",
          "md5": "bcb75d9b5189a859b827f45d25fbcb01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v152.jar",
          "url": "tiled-v152.jar",
          "size": 42985,
          "sha512": "774beac9d9ceac7d454c569edc49b2f3a0431bfd22dbde12eba46e87455cb1c01ace489245c28f1addde04a05abd3368cb1f7212de37194398f8079d8e7ff743",
          "sha256": "116890fc2bfc21786f805849e9badaeac3e212d689f60d93795a5512cf8b30ef",
          "sha1": "5020a957c7bf1696212afca0175969eddb4bbf7f",
          "md5": "bcb75d9b5189a859b827f45d25fbcb01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v152-sources.jar",
          "url": "tiled-v152-sources.jar",
          "size": 23367,
          "sha512": "dae00faf385e6130099a84e48927cca3d7d0938e5f6edd727533db9f3c56e712bf07807ccc0ff6e7c9c3d912fe559b482d5516c9f830d48948c644f54c8dfde7",
          "sha256": "3b993881f52420b0acc9a3ea3511418fed37b0ec4d576d54566e14ee0104dc5c",
          "sha1": "7716d249a73b6403610e92ea6d29577ade64ecf5",
          "md5": "c490dbc3379b47d33936f46831c9b12e"
        }
      ]
    }
  ]
}
