{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-android",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-android-v156.1.jar",
          "url": "natives-freetype-android-v156.1.jar",
          "size": 991652,
          "sha512": "6caf5a77c29e76157ca1e863783ecb266e3a6cc11ad323d4a2f7731b258f1960957afa0f53ded71105ae5b16d902d10fba4ee8b431c6b74895194ff58dd17e4b",
          "sha256": "8eddc5e7fa7bafab7f39f94232a116c117dddb17313f8fe88e2723afbd642312",
          "sha1": "68e3c5a7cdcc5f989852ad6b6dffb3543795399d",
          "md5": "9d03ea287fc051994152b1e49102f129"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-android-v156.1.jar",
          "url": "natives-freetype-android-v156.1.jar",
          "size": 991652,
          "sha512": "6caf5a77c29e76157ca1e863783ecb266e3a6cc11ad323d4a2f7731b258f1960957afa0f53ded71105ae5b16d902d10fba4ee8b431c6b74895194ff58dd17e4b",
          "sha256": "8eddc5e7fa7bafab7f39f94232a116c117dddb17313f8fe88e2723afbd642312",
          "sha1": "68e3c5a7cdcc5f989852ad6b6dffb3543795399d",
          "md5": "9d03ea287fc051994152b1e49102f129"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-android-v156.1-sources.jar",
          "url": "natives-freetype-android-v156.1-sources.jar",
          "size": 991652,
          "sha512": "0291eb9eea2bb3463df55db4972f3735e525e6e6008f33f259ec0a947d50d45c593601de1c8b4840da09ef8f101714ed5824ebe962ba2934006dac8a9cf8075f",
          "sha256": "6b6bcd744225e332f84db9768be68948e35bc2518a02a66db23d3714b3e8a8f6",
          "sha1": "b248643f7cd770fb1949733c3dc8ceba3fed5a91",
          "md5": "451cb5d8253c41a9a2bf04dc6a21d78c"
        }
      ]
    }
  ]
}
