{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v153",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v153.jar",
          "url": "backends-v153.jar",
          "size": 261,
          "sha512": "f38387998dfc1a081392f20109c275ab1583ad89863e5649b0d64d7f229472e7aff8571cdc9a909255534b911e8bbbb74bace4ce350d6446c2bb6e5e50275b67",
          "sha256": "9693c8f0e19431593946f7e5bca81f82bc486aeabcd81a63244f92e95550aa3f",
          "sha1": "c56a0201dfa306b12933ae8d5009b1682ffd274e",
          "md5": "410304f94a07aa50a692bbe271da0265"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v153.jar",
          "url": "backends-v153.jar",
          "size": 261,
          "sha512": "f38387998dfc1a081392f20109c275ab1583ad89863e5649b0d64d7f229472e7aff8571cdc9a909255534b911e8bbbb74bace4ce350d6446c2bb6e5e50275b67",
          "sha256": "9693c8f0e19431593946f7e5bca81f82bc486aeabcd81a63244f92e95550aa3f",
          "sha1": "c56a0201dfa306b12933ae8d5009b1682ffd274e",
          "md5": "410304f94a07aa50a692bbe271da0265"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v153-sources.jar",
          "url": "backends-v153-sources.jar",
          "size": 261,
          "sha512": "f38387998dfc1a081392f20109c275ab1583ad89863e5649b0d64d7f229472e7aff8571cdc9a909255534b911e8bbbb74bace4ce350d6446c2bb6e5e50275b67",
          "sha256": "9693c8f0e19431593946f7e5bca81f82bc486aeabcd81a63244f92e95550aa3f",
          "sha1": "c56a0201dfa306b12933ae8d5009b1682ffd274e",
          "md5": "410304f94a07aa50a692bbe271da0265"
        }
      ]
    }
  ]
}
