{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "tiled",
    "version": "v154.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiled-v154.2.jar",
          "url": "tiled-v154.2.jar",
          "size": 42985,
          "sha512": "8750f5a1e37815ff7ba1a18e7e98543d26574f2c45eafe61b14f0a2b8141f8ed2a3f05370acf4be2b8189388f4bf03e3939533b68d9316d3dd6fcb254621951b",
          "sha256": "71138db7ddda80a978dc8a3e7aaa733333255db1c057e7c8f183c4bdd8ad9581",
          "sha1": "a441c044b56b0acedc12091bd9ad6081bccccb60",
          "md5": "059d6a0567b6dac922ccf34f3ed778fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v154.2.jar",
          "url": "tiled-v154.2.jar",
          "size": 42985,
          "sha512": "8750f5a1e37815ff7ba1a18e7e98543d26574f2c45eafe61b14f0a2b8141f8ed2a3f05370acf4be2b8189388f4bf03e3939533b68d9316d3dd6fcb254621951b",
          "sha256": "71138db7ddda80a978dc8a3e7aaa733333255db1c057e7c8f183c4bdd8ad9581",
          "sha1": "a441c044b56b0acedc12091bd9ad6081bccccb60",
          "md5": "059d6a0567b6dac922ccf34f3ed778fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v154.2-sources.jar",
          "url": "tiled-v154.2-sources.jar",
          "size": 23367,
          "sha512": "9413a415cde80eb6644eebdac322988e7432fa07d7b5dfa73af713d0071ccb6de4f1847cc147d28af675544e8e84d2cd458af1ce8084f0d06f47cd598ef9035e",
          "sha256": "7a89f836bff2571d7f8c0ec2b8d6c5f3f4ce3a341fdc52757c64e119760d0d57",
          "sha1": "9b60c7b4e942e349264fc911e2705958cd42d187",
          "md5": "c7cdd35cd4c994acc193546af76eb2e6"
        }
      ]
    }
  ]
}
