{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v151.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v151.1.jar",
          "url": "natives-freetype-desktop-v151.1.jar",
          "size": 1098026,
          "sha512": "388ef6d99c17eacdb17d194f0ddf83d97e9d6cd3d3af026afa93ae334443fdbff342bdfaceb2e8d18fa340c3827f8386533f2ab9c37ffa11cb79f745b7cb3632",
          "sha256": "5fa4f7710a2281e8f78a48d9675a7bb7b9c05d149219ce5e83e72b7fded5b543",
          "sha1": "f023b3ab638e94662a3ee9fb14a08115f31d39f5",
          "md5": "408226d3be204f2060b59d0ef6c70439"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v151.1.jar",
          "url": "natives-freetype-desktop-v151.1.jar",
          "size": 1098026,
          "sha512": "388ef6d99c17eacdb17d194f0ddf83d97e9d6cd3d3af026afa93ae334443fdbff342bdfaceb2e8d18fa340c3827f8386533f2ab9c37ffa11cb79f745b7cb3632",
          "sha256": "5fa4f7710a2281e8f78a48d9675a7bb7b9c05d149219ce5e83e72b7fded5b543",
          "sha1": "f023b3ab638e94662a3ee9fb14a08115f31d39f5",
          "md5": "408226d3be204f2060b59d0ef6c70439"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v151.1-sources.jar",
          "url": "natives-freetype-desktop-v151.1-sources.jar",
          "size": 1098026,
          "sha512": "c9fd7e01d1b74b66b2f1832e920100eb7ab5ac7194f093c035bc920c7c74e360d8c5d18802ce13281eab5dd347e7aeb7af291cf4f2d320af6b872ba3e60d7827",
          "sha256": "268fcb03684617337e83bc087f018b93846998acc602678bf9246ca86ded512f",
          "sha1": "b8b493f9d6807961cfa4d570c87d7eeedef904d1",
          "md5": "4fba185a1d087d0b06047b151321b1f4"
        }
      ]
    }
  ]
}
