{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v155",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.jar",
          "url": "natives-freetype-desktop-v155.jar",
          "size": 1098026,
          "sha512": "b90b76ea987e64488cbf30c8531930279bed0694d55b6006ab078898c36f558b9895fb082f8d5e44b915d3a65a1c31a2981ada195c04752e726d90953f989df0",
          "sha256": "d761769351097934ced58394a6c48b29386bba3a8c8084ab5c334511a9519b8c",
          "sha1": "279813241f3fbe83e43d53362eec6fcbfcda888d",
          "md5": "1d6d8fe0b0572795c55f6f409666330c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.jar",
          "url": "natives-freetype-desktop-v155.jar",
          "size": 1098026,
          "sha512": "b90b76ea987e64488cbf30c8531930279bed0694d55b6006ab078898c36f558b9895fb082f8d5e44b915d3a65a1c31a2981ada195c04752e726d90953f989df0",
          "sha256": "d761769351097934ced58394a6c48b29386bba3a8c8084ab5c334511a9519b8c",
          "sha1": "279813241f3fbe83e43d53362eec6fcbfcda888d",
          "md5": "1d6d8fe0b0572795c55f6f409666330c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155-sources.jar",
          "url": "natives-freetype-desktop-v155-sources.jar",
          "size": 1098026,
          "sha512": "41a050fa93648f57ecf44a336a16ea7754ed7407fa7d3ebb292938bfd9cfdb7ded64cbce67758f2c68a24f236c41f8d5ae9bc7d78f09848b65a4319d61391b97",
          "sha256": "7ec3baaa55cbedce9a2be86b71a450eab4607045b6fc4c3320ef5921247ff39d",
          "sha1": "78d57b2b24eee0eac5e1c74e4f20f78e90dcc6d9",
          "md5": "4217cf6d0b6564c02f05fbe6bc014087"
        }
      ]
    }
  ]
}
