{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v155",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v155.jar",
          "url": "backend-robovm-v155.jar",
          "size": 80682,
          "sha512": "b159bc7ee90b27496f65a9a7fb1cb3481b0587d37360b7c703f6eaa64373bda3d9d9f5ef199e8579c3529226dd27f0458e868b84aa359d36d8336b813715fb80",
          "sha256": "6940ff11e377ff2b5ecb153208006c2b05d97ca3f6cec3fc4c9f2288f644b122",
          "sha1": "30a72fc7155784a8a71c32cd627a5c5fea8a88c5",
          "md5": "589f24db4cf1ee05e563dc19cc25c565"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v155.jar",
          "url": "backend-robovm-v155.jar",
          "size": 80682,
          "sha512": "b159bc7ee90b27496f65a9a7fb1cb3481b0587d37360b7c703f6eaa64373bda3d9d9f5ef199e8579c3529226dd27f0458e868b84aa359d36d8336b813715fb80",
          "sha256": "6940ff11e377ff2b5ecb153208006c2b05d97ca3f6cec3fc4c9f2288f644b122",
          "sha1": "30a72fc7155784a8a71c32cd627a5c5fea8a88c5",
          "md5": "589f24db4cf1ee05e563dc19cc25c565"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v155-sources.jar",
          "url": "backend-robovm-v155-sources.jar",
          "size": 45852,
          "sha512": "b27aa7067cdfed755c23b44a74a9a7b960964c45da7a8fcdcb828ea7e65598ab1eb337999b65102d976a931accc62ed1f6cd4bbc3f42b7fb53ad5a202e4dd6ae",
          "sha256": "6b6f3c077c0dd790009ec40b1c841375c59d5caac56efd88287e05bba3f1d94b",
          "sha1": "083e1ab183f52e72191fad35c4b0bacea7e04893",
          "md5": "334255e06f64d03315b9e2f48692d4eb"
        }
      ]
    }
  ]
}
