{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v153",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v153.jar",
          "url": "natives-freetype-desktop-v153.jar",
          "size": 1098026,
          "sha512": "b9dfb4bf6e7784301ca850f2a0a06482e336ccf9ed46c284ec88d358266e34b3ec9f3b421e268b188e1c18ce01a67898ea4fe6524b5e0c5f4f28bf5bdb072810",
          "sha256": "b6214ed1128a2729b6de1b17571cbc8f03a9b0ed616bf8b1d536368993a723e1",
          "sha1": "0e7ee34b5bb9b34611812cf64661d2714fcbb1c0",
          "md5": "b43c6450743532246c817bf82a98b0a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v153.jar",
          "url": "natives-freetype-desktop-v153.jar",
          "size": 1098026,
          "sha512": "b9dfb4bf6e7784301ca850f2a0a06482e336ccf9ed46c284ec88d358266e34b3ec9f3b421e268b188e1c18ce01a67898ea4fe6524b5e0c5f4f28bf5bdb072810",
          "sha256": "b6214ed1128a2729b6de1b17571cbc8f03a9b0ed616bf8b1d536368993a723e1",
          "sha1": "0e7ee34b5bb9b34611812cf64661d2714fcbb1c0",
          "md5": "b43c6450743532246c817bf82a98b0a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v153-sources.jar",
          "url": "natives-freetype-desktop-v153-sources.jar",
          "size": 1098026,
          "sha512": "b371d5d79bee8ca30e093274fc2476080f6d5337b1e78d024b58f51679ea2341303bdc08ec7008b278a8a5612d68e3e8d7a305747e9f9c24a3bcf942732b71af",
          "sha256": "ef43c3dec08c2af672fec288f73c54451daf1eadd49354b37d25554367c692af",
          "sha1": "fe76079afc83a2096f9a99c0b6bc78f3ea1856d6",
          "md5": "97d890a10bdaf69844966338f4dca3e9"
        }
      ]
    }
  ]
}
