{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v155",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v155.jar",
          "url": "backend-sdl-v155.jar",
          "size": 3812401,
          "sha512": "efe325eca9958e78a1db3494445a3190aecff075ee6e25a84054e406cce3a0e74df6362ed67f58a85246fec5fa51fd4ec920236cbe897a297debcb8b070741d2",
          "sha256": "07254eed284211e7c2c509aa954c15cbacfa0981c0c0b66b74765f1835df342d",
          "sha1": "2cb0f898dd08626af1527ad2f4dcde15a833e955",
          "md5": "ace680c55daa36a5e93cb961fde57ded"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v155.jar",
          "url": "backend-sdl-v155.jar",
          "size": 3812401,
          "sha512": "efe325eca9958e78a1db3494445a3190aecff075ee6e25a84054e406cce3a0e74df6362ed67f58a85246fec5fa51fd4ec920236cbe897a297debcb8b070741d2",
          "sha256": "07254eed284211e7c2c509aa954c15cbacfa0981c0c0b66b74765f1835df342d",
          "sha1": "2cb0f898dd08626af1527ad2f4dcde15a833e955",
          "md5": "ace680c55daa36a5e93cb961fde57ded"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v155-sources.jar",
          "url": "backend-sdl-v155-sources.jar",
          "size": 3793309,
          "sha512": "218acc0371557362328a02680773cc61f332efac0da114ede56da44ddc6cedfbaff8981e049b79c1249732c73e6606197bb558b8aec5ee8cec25028feb168af0",
          "sha256": "22308e4a06d667a22d68b2ff327947f7f8ad2d06785ac7d68826ef62e0b64111",
          "sha1": "4dbbd7c22f3c64850d3c8678e2136733adb5a8f1",
          "md5": "b9a95119f454788ddefbbd3fb663c7b7"
        }
      ]
    }
  ]
}
