{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-android",
    "version": "v155.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-android-v155.1.jar",
          "url": "natives-android-v155.1.jar",
          "size": 1072621,
          "sha512": "260c37459e09591a0f94442c86555a4619b5868e8f7055b1ff1c4b529977c3edbb0e009a7a6a456cc42a2f0b95e24c1b1db99361b0cd7d7d3d3f89a6638d66a5",
          "sha256": "fe2af84034e4006cacd7831e17e15a268235560e2aec12ef8fbfc2546ba08e55",
          "sha1": "03b385e8ffa04e6640dacb4aebc29e564086561d",
          "md5": "09a5b3f55fa24082d2d1d098356d508e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-android-v155.1.jar",
          "url": "natives-android-v155.1.jar",
          "size": 1072621,
          "sha512": "260c37459e09591a0f94442c86555a4619b5868e8f7055b1ff1c4b529977c3edbb0e009a7a6a456cc42a2f0b95e24c1b1db99361b0cd7d7d3d3f89a6638d66a5",
          "sha256": "fe2af84034e4006cacd7831e17e15a268235560e2aec12ef8fbfc2546ba08e55",
          "sha1": "03b385e8ffa04e6640dacb4aebc29e564086561d",
          "md5": "09a5b3f55fa24082d2d1d098356d508e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-android-v155.1-sources.jar",
          "url": "natives-android-v155.1-sources.jar",
          "size": 1072621,
          "sha512": "8c7129ab2e641046238f29f524dd94300c7c077a507b0923dacb0b39d9b1e1d9d65445ca591227f0c5d76b1c43113874b9135560b534368118bb554e81fb8424",
          "sha256": "1c5f12d183376c85d0d8ccefe13385e217ea63858b04b37ea14c7354bf9d8b4e",
          "sha1": "720cf24c0f62eee052bf767655c6310f3ca9e3fb",
          "md5": "51c2bda0871ae0c2bd957c7a1cfaa323"
        }
      ]
    }
  ]
}
