{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v154",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v154.jar",
          "url": "backend-sdl-v154.jar",
          "size": 3812401,
          "sha512": "14e79b9e727cbd26e2de3a86875e8274455728c0a32b6548f7705528add1f431d2004c58e3a7f4b15bb1827cbf24ea5fd2fcce09d0ef7879e9e7e138b36ae02c",
          "sha256": "aa2f13bbbfc97ea1db69266809062af5b34235604fca3b639c2aaa91584e777a",
          "sha1": "3a5c3479101ce62efdbec9eabdf448b33c6419b2",
          "md5": "18d5ddd999da736a4da596c0876d4828"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v154.jar",
          "url": "backend-sdl-v154.jar",
          "size": 3812401,
          "sha512": "14e79b9e727cbd26e2de3a86875e8274455728c0a32b6548f7705528add1f431d2004c58e3a7f4b15bb1827cbf24ea5fd2fcce09d0ef7879e9e7e138b36ae02c",
          "sha256": "aa2f13bbbfc97ea1db69266809062af5b34235604fca3b639c2aaa91584e777a",
          "sha1": "3a5c3479101ce62efdbec9eabdf448b33c6419b2",
          "md5": "18d5ddd999da736a4da596c0876d4828"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v154-sources.jar",
          "url": "backend-sdl-v154-sources.jar",
          "size": 3793309,
          "sha512": "1970dcda9b0ae8ba6e47251ba4e4e8da54e62bf8a78c6456c488a2a39707905b71792dac5b9da51b59a270a9410493ff5aa4fd771ec22e21c66c402d42fd53f5",
          "sha256": "7846d3a613b4c03f5ef3f540142d107ba043fa13891b5c4f5de5530f32a017d7",
          "sha1": "a316a8091e68985f81f073b836477ac4d243da81",
          "md5": "9884c5d3ee04ac7c7c0a5eae448b6d3e"
        }
      ]
    }
  ]
}
