{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v152",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v152.jar",
          "url": "natives-box2d-android-v152.jar",
          "size": 411485,
          "sha512": "3a957e3c13e4a602a66538e2e7b05a7590dba3a2903635097cb13e170aea02c89ae3eb85b2481b32da8f26b7fd0318fcbb196fa22126e7e18cb36959812689ac",
          "sha256": "b99bee76830cfc414a05eff16368df2d4a014156127b3b9be76a14f07fd6f858",
          "sha1": "9b548bb971d023877a4dcafc0864a96abe73eeb5",
          "md5": "f5123ca26fc4e606cb72d127377ed407"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v152.jar",
          "url": "natives-box2d-android-v152.jar",
          "size": 411485,
          "sha512": "3a957e3c13e4a602a66538e2e7b05a7590dba3a2903635097cb13e170aea02c89ae3eb85b2481b32da8f26b7fd0318fcbb196fa22126e7e18cb36959812689ac",
          "sha256": "b99bee76830cfc414a05eff16368df2d4a014156127b3b9be76a14f07fd6f858",
          "sha1": "9b548bb971d023877a4dcafc0864a96abe73eeb5",
          "md5": "f5123ca26fc4e606cb72d127377ed407"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v152-sources.jar",
          "url": "natives-box2d-android-v152-sources.jar",
          "size": 411485,
          "sha512": "138e58fa6b63d93a9dbcf76c137ff51c8a0931d6ea27ffad7e212fc95d661377aafd1c45baafdc82f78c6bae4a701e9669f0c2cea46c4bfaa5f47fce3b2005b4",
          "sha256": "9d0f8b21562f4d697397228759cc2dd2bc212a745da54d485ca1f501fd9281bd",
          "sha1": "8a612dedfe53a124dd209b455afac469e62361db",
          "md5": "1558449fe2d955c53a58baf1a32c8218"
        }
      ]
    }
  ]
}
