{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v154.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v154.3.jar",
          "url": "natives-box2d-android-v154.3.jar",
          "size": 411485,
          "sha512": "ebf35bc93a5c33449a6809c69f5d37c09a248ace76578eaa06b06d857f13b7ede9354839a4ccdc5b32ca534c1fb2aadd95d09278e22dde23a0d2b51e7d2e9ea8",
          "sha256": "233a75339443bd1a06538fdecb346f9414dc2d1166d5cb1baea425034814e83c",
          "sha1": "1823c0fa5dd53fd30b437b15462e917f4d0785a5",
          "md5": "6a65d727b9a4945dfbce73ac077545a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v154.3.jar",
          "url": "natives-box2d-android-v154.3.jar",
          "size": 411485,
          "sha512": "ebf35bc93a5c33449a6809c69f5d37c09a248ace76578eaa06b06d857f13b7ede9354839a4ccdc5b32ca534c1fb2aadd95d09278e22dde23a0d2b51e7d2e9ea8",
          "sha256": "233a75339443bd1a06538fdecb346f9414dc2d1166d5cb1baea425034814e83c",
          "sha1": "1823c0fa5dd53fd30b437b15462e917f4d0785a5",
          "md5": "6a65d727b9a4945dfbce73ac077545a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v154.3-sources.jar",
          "url": "natives-box2d-android-v154.3-sources.jar",
          "size": 411485,
          "sha512": "1c7a01da3e23a8396857cd128e24e08a1a38a24bc577695025f020310f4c8299d2e9c11de987d558148eb30facc8a1b8fd063f1954a41888c590c2c9acf4bc84",
          "sha256": "1aa04db92c77eacbca716c1eae77f55ee8a9ee2d220970928daa1a4ec676650c",
          "sha1": "c70883ed445096c404e64e81ff2c63f119318e56",
          "md5": "f484fd06dbf444501e21f0a560d6817f"
        }
      ]
    }
  ]
}
