{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v151.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v151.1.jar",
          "url": "natives-box2d-android-v151.1.jar",
          "size": 411485,
          "sha512": "7249a957523a326080181c12623ee0a110d9c916e6536393e5a95e57fb6f67f81b3c0b0fa030317085f6963d444c7fb18b686b714ec3bfc3a7af3c4e6a2d72b3",
          "sha256": "ac3a382ec133a4f44500d47b6621386455d3c5f9841c714a2e7fd8b1ed7f02cf",
          "sha1": "0124e4ad5a464205a9a2eabccb98d6d7a67b3e27",
          "md5": "706b29f37cee032bdd5dd133769601dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v151.1.jar",
          "url": "natives-box2d-android-v151.1.jar",
          "size": 411485,
          "sha512": "7249a957523a326080181c12623ee0a110d9c916e6536393e5a95e57fb6f67f81b3c0b0fa030317085f6963d444c7fb18b686b714ec3bfc3a7af3c4e6a2d72b3",
          "sha256": "ac3a382ec133a4f44500d47b6621386455d3c5f9841c714a2e7fd8b1ed7f02cf",
          "sha1": "0124e4ad5a464205a9a2eabccb98d6d7a67b3e27",
          "md5": "706b29f37cee032bdd5dd133769601dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v151.1-sources.jar",
          "url": "natives-box2d-android-v151.1-sources.jar",
          "size": 411485,
          "sha512": "4592f3681f04e1af0e62955a7e9caa855cd5ea65af155d40ccbc5efdedb8b58444b7edac53c470e0358d1d248929b7b161768e3cb4f5114639d0ae595c3eef59",
          "sha256": "d52ba0dd4fb1e15603fbfbb14ce334fc82cdc4582849cc6d707331bd8b00b1e8",
          "sha1": "996c1064983a8cec766e8ad271ee224061bd96dc",
          "md5": "2b94b9f9e4f51dd7866480e8f9aee671"
        }
      ]
    }
  ]
}
