{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-ios",
    "version": "v154.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v154.3.jar",
          "url": "natives-box2d-ios-v154.3.jar",
          "size": 2384392,
          "sha512": "eb52032260d19808579ac25dd747bf8f8c63d066aa750a5f8eb1b516e9284e4174f4c0c2c7e6761c7f5f95673127f508cd1e1cb076b5e231e3bce03dc5d69485",
          "sha256": "aadaefb84d6c1377f4553402f7c827a7c9ba84638ea571621aba5cbcfa4d33ac",
          "sha1": "6a5a9871d1e2802fab874f85db751801ed41df83",
          "md5": "26d54f46f5074b715890a8d4f9977c74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v154.3.jar",
          "url": "natives-box2d-ios-v154.3.jar",
          "size": 2384392,
          "sha512": "eb52032260d19808579ac25dd747bf8f8c63d066aa750a5f8eb1b516e9284e4174f4c0c2c7e6761c7f5f95673127f508cd1e1cb076b5e231e3bce03dc5d69485",
          "sha256": "aadaefb84d6c1377f4553402f7c827a7c9ba84638ea571621aba5cbcfa4d33ac",
          "sha1": "6a5a9871d1e2802fab874f85db751801ed41df83",
          "md5": "26d54f46f5074b715890a8d4f9977c74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v154.3-sources.jar",
          "url": "natives-box2d-ios-v154.3-sources.jar",
          "size": 2384392,
          "sha512": "859824519a60dad9c9658f95901e8cec34cd102a30c6ace5053ce4a66ff8ab831485da2d65d244f7061a54e5bb4f99ffe86de7f94afe1009d971a21ac04e2cee",
          "sha256": "711bca4ca3f41ee71477fef6f18baa405ee839be1bfd30da8886abf8357e1a7e",
          "sha1": "f455866913fbf046fd875513a6f019a37e47b0e9",
          "md5": "046ab704082a6e339b8cf83858957a7d"
        }
      ]
    }
  ]
}
