{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-desktop",
    "version": "v155.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v155.4.jar",
          "url": "natives-box2d-desktop-v155.4.jar",
          "size": 512159,
          "sha512": "57e3d59cfed36896a18b6916a4343bd13bc4e6f50a54bf979d932dc9fb5ad3fc14a09fac987370dfc97d263a3ef363a5cfdae2de1d91abe32196a42deb33f96d",
          "sha256": "f69d454d09367245057b921278aab2d6393aabad29edaedccd69836ccec739ec",
          "sha1": "0deedd6f222d0ac0a9a2ef7f2deba3a1f8624562",
          "md5": "6e0117423fa259adc79634bcdaa5e5a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v155.4.jar",
          "url": "natives-box2d-desktop-v155.4.jar",
          "size": 512159,
          "sha512": "57e3d59cfed36896a18b6916a4343bd13bc4e6f50a54bf979d932dc9fb5ad3fc14a09fac987370dfc97d263a3ef363a5cfdae2de1d91abe32196a42deb33f96d",
          "sha256": "f69d454d09367245057b921278aab2d6393aabad29edaedccd69836ccec739ec",
          "sha1": "0deedd6f222d0ac0a9a2ef7f2deba3a1f8624562",
          "md5": "6e0117423fa259adc79634bcdaa5e5a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v155.4-sources.jar",
          "url": "natives-box2d-desktop-v155.4-sources.jar",
          "size": 512159,
          "sha512": "0583348f69689b5fe917b7b8b1ee25a78e29d0d690d9aee18829a09e974e55e01e1de3890a149c0151ac18da0735af35b93b2d801fbaf5b72a02f63993c092e3",
          "sha256": "7618d39de30e7905d730f355c0a880b41d29b4ec9a7de45fa9e06de271f6fb4a",
          "sha1": "30ba13c0bc3c5590dd3479423c9a56712a776d90",
          "md5": "a0c8637003793f8771a8e6340d1aec13"
        }
      ]
    }
  ]
}
