{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "core",
    "version": "v155.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.yawk.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "54b75cbd1207ef1fd5cff517cbd188e763c85baa"
          }
        }
      ],
      "files": [
        {
          "name": "core-v155.2.jar",
          "url": "core-v155.2.jar",
          "size": 5584412,
          "sha512": "c683d4126dd43c59312812582e7917f1973ce314f0d641287140a37c0d4beaf7d634fab354765d6cc7bcf313998ca65f8a904629971fa3fe7fc6ac00f1a3fc27",
          "sha256": "1290fc631212161ec76638b875182a3c775448615ed9b79cbfda127cc67b6f00",
          "sha1": "1658ee8ea28bb95823d4a3bfb39587ee71b0c708",
          "md5": "a77178f7c18de22eb7c50fad5dc30c7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.yawk.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v155.2"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "54b75cbd1207ef1fd5cff517cbd188e763c85baa"
          }
        }
      ],
      "files": [
        {
          "name": "core-v155.2.jar",
          "url": "core-v155.2.jar",
          "size": 5584412,
          "sha512": "c683d4126dd43c59312812582e7917f1973ce314f0d641287140a37c0d4beaf7d634fab354765d6cc7bcf313998ca65f8a904629971fa3fe7fc6ac00f1a3fc27",
          "sha256": "1290fc631212161ec76638b875182a3c775448615ed9b79cbfda127cc67b6f00",
          "sha1": "1658ee8ea28bb95823d4a3bfb39587ee71b0c708",
          "md5": "a77178f7c18de22eb7c50fad5dc30c7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v155.2-sources.jar",
          "url": "core-v155.2-sources.jar",
          "size": 1511750,
          "sha512": "608c9a06450ad07ce084311aed62c490b0652afa9216a8f310ea7ff470022aea56efcd70988512d17272e7ab779ed2aed751b3701b283e7b916dc4c6320b7711",
          "sha256": "54b01a931fa231aea956e4233970504a9af8d7ec668fd865a3fc78a7238caabd",
          "sha1": "26394336d16f3b13268cebe26f981e209d10fb4d",
          "md5": "b990078764c9c663acbe01b091d60643"
        }
      ]
    }
  ]
}
