{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v152.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v152.1.jar",
          "url": "natives-freetype-desktop-v152.1.jar",
          "size": 1098026,
          "sha512": "52f015d187085dfe23714b19818dfe574ab215977fd8aa3113800cb123d0b2fb35813056302e2890ba8a4c86485e09be4233f1fce7f4721815d5c70b526321d5",
          "sha256": "9ecdc04e18082cf762516116f8f2ca9cf4676b8e9afc6199e1a3187eb274dd30",
          "sha1": "efb2eae6cc83bc16d5d8a349b209102822978203",
          "md5": "bf1f7fbeb61642ea8afbdefc2f6a85e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v152.1.jar",
          "url": "natives-freetype-desktop-v152.1.jar",
          "size": 1098026,
          "sha512": "52f015d187085dfe23714b19818dfe574ab215977fd8aa3113800cb123d0b2fb35813056302e2890ba8a4c86485e09be4233f1fce7f4721815d5c70b526321d5",
          "sha256": "9ecdc04e18082cf762516116f8f2ca9cf4676b8e9afc6199e1a3187eb274dd30",
          "sha1": "efb2eae6cc83bc16d5d8a349b209102822978203",
          "md5": "bf1f7fbeb61642ea8afbdefc2f6a85e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v152.1-sources.jar",
          "url": "natives-freetype-desktop-v152.1-sources.jar",
          "size": 1098026,
          "sha512": "02f12293b83fb123a3eebf7b1efdb7b02444fdecdbefdac24fd00afc058fe5ff96bfaf4a5031059270fa7a1db841d1dbce62b76f76adf8d42d1d3ec3f6b52420",
          "sha256": "e8cf510e8112f0645dd72ba8e07384bd04727325c0f0b0549dfddf8ef19b2929",
          "sha1": "bf992cc5d1e534d8895f7bdfa6facfe8c1480706",
          "md5": "b3bf1979037e5932a0d5366c769912ff"
        }
      ]
    }
  ]
}
