{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-desktop",
    "version": "v151.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v151.1.jar",
          "url": "natives-box2d-desktop-v151.1.jar",
          "size": 512159,
          "sha512": "c320f9e316cf0f00d5acec371010dab690b6ff2afe2317a43b6376d8a10177b4e7a1e704c26abde0cac766bb0d90d279fa84dadf8983df29f530f3acfbef1a2f",
          "sha256": "dd6614d7e3b0c07d7a0aca9d7f216b6b95a8184228ba3fbdaa09153218f65cec",
          "sha1": "b3e62740e5ec41e0afc4724555a8eeae8bf63fa3",
          "md5": "f495de98a12ba634ca7a556b02a1c456"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v151.1.jar",
          "url": "natives-box2d-desktop-v151.1.jar",
          "size": 512159,
          "sha512": "c320f9e316cf0f00d5acec371010dab690b6ff2afe2317a43b6376d8a10177b4e7a1e704c26abde0cac766bb0d90d279fa84dadf8983df29f530f3acfbef1a2f",
          "sha256": "dd6614d7e3b0c07d7a0aca9d7f216b6b95a8184228ba3fbdaa09153218f65cec",
          "sha1": "b3e62740e5ec41e0afc4724555a8eeae8bf63fa3",
          "md5": "f495de98a12ba634ca7a556b02a1c456"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v151.1-sources.jar",
          "url": "natives-box2d-desktop-v151.1-sources.jar",
          "size": 512159,
          "sha512": "475eec3b66a28743f09d396a09d7f616abf946fe3d7fecfe66b95d081948ea20444c4ea0889edbfb802b7b097ef8b6ad71d10c2153600e14cc24f44be7e59173",
          "sha256": "c2fdc62f866b4f607f80dbccacbb4c323a221c5f8733091f7dba415b357bbb94",
          "sha1": "2163702958dc62742b7016f02ff9a12296a49a31",
          "md5": "4c7bfa758315ad19659e8d3ec74dffb7"
        }
      ]
    }
  ]
}
