{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-ios",
    "version": "v152",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v152.jar",
          "url": "natives-box2d-ios-v152.jar",
          "size": 2384392,
          "sha512": "6fed773c90935470f87f0599fff113722a5ab96aba77c1f4e9a0d4ccb56936c6cff1965ce39a65f307eb0ffc1c0d463abea698e1f8c5aa71a1380e14ebdfff8c",
          "sha256": "174ea0230675288e26787ae3f463f0d9dd889315cc0104747ca626e110fdc136",
          "sha1": "b3d3f4be9bc92c901cb510c70cc09e6ba9e1a984",
          "md5": "54392acfe572d83602a80b969fcc361e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v152.jar",
          "url": "natives-box2d-ios-v152.jar",
          "size": 2384392,
          "sha512": "6fed773c90935470f87f0599fff113722a5ab96aba77c1f4e9a0d4ccb56936c6cff1965ce39a65f307eb0ffc1c0d463abea698e1f8c5aa71a1380e14ebdfff8c",
          "sha256": "174ea0230675288e26787ae3f463f0d9dd889315cc0104747ca626e110fdc136",
          "sha1": "b3d3f4be9bc92c901cb510c70cc09e6ba9e1a984",
          "md5": "54392acfe572d83602a80b969fcc361e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v152-sources.jar",
          "url": "natives-box2d-ios-v152-sources.jar",
          "size": 2384392,
          "sha512": "9b98f79e4f759935aedc6297b04438f8d1ec26221e6d9abcc59c5605a00fc2c9f61c7741ccf25d48fcc67e6e35a9c82d8accab53ad4c199ef73a1ea27e07bbe2",
          "sha256": "16ad31f2ccec5cb66b31aa4e5acc8763c982e052ead9b51ee437f1586c62409a",
          "sha1": "868374d6cfb9b3eccf50f564cbf320b26aeb1831",
          "md5": "b8eb9ef9df49e46d6ff4229cf8fb6f38"
        }
      ]
    }
  ]
}
