{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "box2d",
    "version": "v154",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "box2d-v154.jar",
          "url": "box2d-v154.jar",
          "size": 58093,
          "sha512": "d4ced8289c7fe5ac0ff24a9080cf77c263647c3e105f89111efef03b28ea4451ed0f81ffe361122929a1a94e18086862e8deff66e37f79145cd11751db256ea6",
          "sha256": "405ac4e68e2e12d26a5650c47550111eb4cf2dcd88a4c53be28226666c10cc1f",
          "sha1": "0a127ee0dd8580316b547e89c11e86dc81208f94",
          "md5": "965dc07bd3851eb1c72cc12fdd16246a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box2d-v154.jar",
          "url": "box2d-v154.jar",
          "size": 58093,
          "sha512": "d4ced8289c7fe5ac0ff24a9080cf77c263647c3e105f89111efef03b28ea4451ed0f81ffe361122929a1a94e18086862e8deff66e37f79145cd11751db256ea6",
          "sha256": "405ac4e68e2e12d26a5650c47550111eb4cf2dcd88a4c53be28226666c10cc1f",
          "sha1": "0a127ee0dd8580316b547e89c11e86dc81208f94",
          "md5": "965dc07bd3851eb1c72cc12fdd16246a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box2d-v154-sources.jar",
          "url": "box2d-v154-sources.jar",
          "size": 52592,
          "sha512": "8bdc05bb3fbf9bcaa1e9d4e6de7ad5f5b89a7deac0af3755894e5133553300083afa35de67ca675a202a9f8985d0ebd27d7eba8a5b2119b2323f7b08a382399b",
          "sha256": "a51788cf266c925ddfabb419be8648e890e9335f8ebe690071961e97298bd065",
          "sha1": "a6358ef4b7ad90dbf2054c9f2bf0481b9dada0cb",
          "md5": "aac2eb8d20a25ccc3a4db229ad9c14c7"
        }
      ]
    }
  ]
}
