{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v154",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v154.jar",
          "url": "natives-box2d-android-v154.jar",
          "size": 411485,
          "sha512": "4b762c1d7632089ef9c431cbc61c6beb783271032483527592c5a94f57c3c13c8e314acc9ce56e6279d39be6ace56176edbd638577c67c336aad983a46dd1c78",
          "sha256": "47084bca1820774f03cb7896e43deac48df18f9fb79641ba1c0b0152b833cfe6",
          "sha1": "6e9369a5620f86a363e0e1699533acde30551a22",
          "md5": "f1aa3ba2bc9bf12a99c63c27711b092e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v154.jar",
          "url": "natives-box2d-android-v154.jar",
          "size": 411485,
          "sha512": "4b762c1d7632089ef9c431cbc61c6beb783271032483527592c5a94f57c3c13c8e314acc9ce56e6279d39be6ace56176edbd638577c67c336aad983a46dd1c78",
          "sha256": "47084bca1820774f03cb7896e43deac48df18f9fb79641ba1c0b0152b833cfe6",
          "sha1": "6e9369a5620f86a363e0e1699533acde30551a22",
          "md5": "f1aa3ba2bc9bf12a99c63c27711b092e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v154-sources.jar",
          "url": "natives-box2d-android-v154-sources.jar",
          "size": 411485,
          "sha512": "84f2d8c2e72b26c1741895941ef05dd9a78138a72a42acbb3ce0bc7176d8ca8833a88d6837c9d7006e4c4cb10f9df27da8797eab6d686063cf72ef5c9c0e3c3d",
          "sha256": "3957847a5174e56d042f487ea44b958b938c762c5bff8bd2b0699680834cf01f",
          "sha1": "5290b17782768d917de9185c8b79a8121566a385",
          "md5": "ad4857ed6af40bbce0ecb7e0f17d4312"
        }
      ]
    }
  ]
}
