{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v149",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v149.jar",
          "url": "natives-box2d-android-v149.jar",
          "size": 411485,
          "sha512": "915b1f25b871297aad041dd8704ed7c2110d1030c8b07f69c5b6eb181b7c7e9c4d94ecc77dad3759b11296925af51b846de9f8fdb52e05ba581729c3b64abc37",
          "sha256": "22e71fdc4497e7f18cf173472f47fb8fc0996dd0c288e3c309ecfa093d45a782",
          "sha1": "707d4fdbe1a80cc93284bb462258f3c4667678f1",
          "md5": "ac274af376d21884b5e71f0499fba684"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v149.jar",
          "url": "natives-box2d-android-v149.jar",
          "size": 411485,
          "sha512": "915b1f25b871297aad041dd8704ed7c2110d1030c8b07f69c5b6eb181b7c7e9c4d94ecc77dad3759b11296925af51b846de9f8fdb52e05ba581729c3b64abc37",
          "sha256": "22e71fdc4497e7f18cf173472f47fb8fc0996dd0c288e3c309ecfa093d45a782",
          "sha1": "707d4fdbe1a80cc93284bb462258f3c4667678f1",
          "md5": "ac274af376d21884b5e71f0499fba684"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v149-sources.jar",
          "url": "natives-box2d-android-v149-sources.jar",
          "size": 411485,
          "sha512": "88746ae91fdbc60316cbb3c2ea37f42ea631dd8157fd365e33c6c85c02182dccb1aff5855be13de40c56a174d5503099f2f4234c480f5f3593644357ee8efd67",
          "sha256": "6be371558d1afabe90f87b22c382b88640646733e42ba0359d3d88eb339e11e6",
          "sha1": "f8d1832869187f087c4606efb4d8f1525caa23c3",
          "md5": "ca2912e155f55a791f3410216f58a858"
        }
      ]
    }
  ]
}
