{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v155.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.4.jar",
          "url": "natives-freetype-desktop-v155.4.jar",
          "size": 1098026,
          "sha512": "15e71fa4b43d935fc1653656e37ec0a3dc0a0f3949ff785ce4b1a007254466021afa99516e9239c58ad43f00766b86ca905d53a90e50e69b8e23b24b8a0dd923",
          "sha256": "04f409afa8221b68f5a3ce3353677ab35d86647627f5427aee5b5aca763319dc",
          "sha1": "bf0584079ed13c3c95a6c585c9e756b9ec9ded18",
          "md5": "9f5a125ea40384fbf9d3ae964ea86d6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.4.jar",
          "url": "natives-freetype-desktop-v155.4.jar",
          "size": 1098026,
          "sha512": "15e71fa4b43d935fc1653656e37ec0a3dc0a0f3949ff785ce4b1a007254466021afa99516e9239c58ad43f00766b86ca905d53a90e50e69b8e23b24b8a0dd923",
          "sha256": "04f409afa8221b68f5a3ce3353677ab35d86647627f5427aee5b5aca763319dc",
          "sha1": "bf0584079ed13c3c95a6c585c9e756b9ec9ded18",
          "md5": "9f5a125ea40384fbf9d3ae964ea86d6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v155.4-sources.jar",
          "url": "natives-freetype-desktop-v155.4-sources.jar",
          "size": 1098026,
          "sha512": "3332de5885f8d622dd478f8742131e8e5324959511803526cd28379cc2e913b31b30f0d56788f7388e99604c65e123d3e21bccff2fce22a58988d9287d521cb8",
          "sha256": "64822cd510f3518a86d29f2c20747ff40104526712262073c8319580522d941d",
          "sha1": "8c644c569493010ba7d8298886e65917850374f2",
          "md5": "ccfec525c3a75e9b06e5df9295a1bbbc"
        }
      ]
    }
  ]
}
