{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "core",
    "version": "v153",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v153.jar",
          "url": "core-v153.jar",
          "size": 5491000,
          "sha512": "625c082ad058b3787d3c88b6bcaa4b7ef8d0d828c1056697c079fe0732470aacc8e4c7fdabac1cfedd50ba2a16bf5841af9295755bf1df09720fdf0f2a51ee74",
          "sha256": "a6ac5491daf4adec762d3049aa65646f6c1f66c65506f4b4ddf29c720be99ca9",
          "sha1": "5a59651c5e88e435233de3f09a33b764b471ba84",
          "md5": "7bcf3867af9286829b51b885576103b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "filedialogs",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v153"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v153.jar",
          "url": "core-v153.jar",
          "size": 5491000,
          "sha512": "625c082ad058b3787d3c88b6bcaa4b7ef8d0d828c1056697c079fe0732470aacc8e4c7fdabac1cfedd50ba2a16bf5841af9295755bf1df09720fdf0f2a51ee74",
          "sha256": "a6ac5491daf4adec762d3049aa65646f6c1f66c65506f4b4ddf29c720be99ca9",
          "sha1": "5a59651c5e88e435233de3f09a33b764b471ba84",
          "md5": "7bcf3867af9286829b51b885576103b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v153-sources.jar",
          "url": "core-v153-sources.jar",
          "size": 1493001,
          "sha512": "84182d4c79ac47cf2b009bb3b2cf9ca15dac4ef70d84cf636fabba8c1faabb3e4da736139e9c6b978d6c3f413c80a74f71c1c19afd738a40708c8cb2b007ddee",
          "sha256": "a6b16482ba6bb70155b52115e1bc270939603510fd46eb1627dccd3763b587e0",
          "sha1": "6ba74546c4fb9a63b8db2f226f7c6029a605d4b4",
          "md5": "05a1fd83f05bceb8197896ccc2241d05"
        }
      ]
    }
  ]
}
