{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v152",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v152.jar",
          "url": "backends-v152.jar",
          "size": 261,
          "sha512": "39242e17acea1741d7228af81337714be1d88b3c8f201e29ee6a798de3fdc3c99a4c3c31656dd96d59401a78f73f16f92088e9addbb8056a00954fda7ee4c2fd",
          "sha256": "0d2fee3f0b7722245fb427a0d6686ed2f044fde1f58ef69d5682a5a7da867867",
          "sha1": "69974a23ef3ccb5fb1a2f89a5ce20241ae7f733e",
          "md5": "2d2adf03dddd7dad3fa8e9c8f4fc4ef9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v152.jar",
          "url": "backends-v152.jar",
          "size": 261,
          "sha512": "39242e17acea1741d7228af81337714be1d88b3c8f201e29ee6a798de3fdc3c99a4c3c31656dd96d59401a78f73f16f92088e9addbb8056a00954fda7ee4c2fd",
          "sha256": "0d2fee3f0b7722245fb427a0d6686ed2f044fde1f58ef69d5682a5a7da867867",
          "sha1": "69974a23ef3ccb5fb1a2f89a5ce20241ae7f733e",
          "md5": "2d2adf03dddd7dad3fa8e9c8f4fc4ef9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v152-sources.jar",
          "url": "backends-v152-sources.jar",
          "size": 261,
          "sha512": "39242e17acea1741d7228af81337714be1d88b3c8f201e29ee6a798de3fdc3c99a4c3c31656dd96d59401a78f73f16f92088e9addbb8056a00954fda7ee4c2fd",
          "sha256": "0d2fee3f0b7722245fb427a0d6686ed2f044fde1f58ef69d5682a5a7da867867",
          "sha1": "69974a23ef3ccb5fb1a2f89a5ce20241ae7f733e",
          "md5": "2d2adf03dddd7dad3fa8e9c8f4fc4ef9"
        }
      ]
    }
  ]
}
