{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "core",
    "version": "v151.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v151.1.jar",
          "url": "core-v151.1.jar",
          "size": 5432880,
          "sha512": "93c75bb106c2dc0ffde5b30eb364a8c2622417c93fca4588149f1404e743c52dc0d989286ac77807342f31b7e55ce44c5618d20bddd257f3cc175b9f62848da4",
          "sha256": "3c22d9ca31e959c880594aae6ec29acca4d5edc09f2ca43c2672904eaa52e2da",
          "sha1": "2c7da57a6c4645761e5f02e38282eed41f9a82c4",
          "md5": "7ec6059697666a35f0c495cb66db79a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "filedialogs",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v151.1"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v151.1.jar",
          "url": "core-v151.1.jar",
          "size": 5432880,
          "sha512": "93c75bb106c2dc0ffde5b30eb364a8c2622417c93fca4588149f1404e743c52dc0d989286ac77807342f31b7e55ce44c5618d20bddd257f3cc175b9f62848da4",
          "sha256": "3c22d9ca31e959c880594aae6ec29acca4d5edc09f2ca43c2672904eaa52e2da",
          "sha1": "2c7da57a6c4645761e5f02e38282eed41f9a82c4",
          "md5": "7ec6059697666a35f0c495cb66db79a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v151.1-sources.jar",
          "url": "core-v151.1-sources.jar",
          "size": 1470623,
          "sha512": "4b62df46bc34aa5aacd2aaef77936063c2d5858469fe7b820a86ed9b12ecb6f90af2c5bbe69f1d8fbcc2f28bfb61e83ad21c4df9cfa32470b3bb899d8e6c40db",
          "sha256": "620473a412e7246d56d0a58501d3613969baac3055b89b34a5eeaf0840c6e7d2",
          "sha1": "f2d922fe8999722a351af1aca16cbdc622a3dfc6",
          "md5": "6e79832d21b4f413fd02446136aee797"
        }
      ]
    }
  ]
}
