{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v149",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v149.jar",
          "url": "natives-freetype-desktop-v149.jar",
          "size": 1098026,
          "sha512": "8dc7068c13bfc8ce96d0355c1a53d9f6d09dbe9b6f53be37dde2437a14f978bc2bdca7cac3a2e62b84a68e4de765a8723f1bb3d99eb788fd0212334cfbbe67f4",
          "sha256": "fc6632b5af1423ff9aaba9cb2c1290f95c1c3f2d8d53e6ac21b89db16bcdb490",
          "sha1": "e5f4f7316c4476cc23cb65478263ee5429e8aa18",
          "md5": "2d249b5b083006c42876983e99b1a84d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v149.jar",
          "url": "natives-freetype-desktop-v149.jar",
          "size": 1098026,
          "sha512": "8dc7068c13bfc8ce96d0355c1a53d9f6d09dbe9b6f53be37dde2437a14f978bc2bdca7cac3a2e62b84a68e4de765a8723f1bb3d99eb788fd0212334cfbbe67f4",
          "sha256": "fc6632b5af1423ff9aaba9cb2c1290f95c1c3f2d8d53e6ac21b89db16bcdb490",
          "sha1": "e5f4f7316c4476cc23cb65478263ee5429e8aa18",
          "md5": "2d249b5b083006c42876983e99b1a84d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v149-sources.jar",
          "url": "natives-freetype-desktop-v149-sources.jar",
          "size": 1098026,
          "sha512": "38ac5df17bc0202d2a5f9a7b2835579af4a8a76e408e7c2965e59e192d847987707ba8c5f7da5e5b8f500cf84a1f1527097b65d0a26c89b7d83f40b45b010846",
          "sha256": "687cf99e5637f2e106a6729cd781a57dc839b5948ac423a9f0dee8b6b1078d93",
          "sha1": "f57b161220d97650875ae7638c889794bce5dd3d",
          "md5": "c5bf96ef16999099f6a4bd132660f59f"
        }
      ]
    }
  ]
}
