{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-desktop",
    "version": "v149",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v149.jar",
          "url": "natives-box2d-desktop-v149.jar",
          "size": 512159,
          "sha512": "f93b004842223ffc71872e7a10b48d6456d7cf559c3f5de017915f6586bc48e9c92d7de3a54995658e61c2a22cd5250e47c98a845fc9b22ef9d93e76bdfd1bce",
          "sha256": "0153e61fb084d7cec918f5ba0f7f968058c5d840f6a6affb39fa772ffb8108ae",
          "sha1": "b62942acd549f2b495547d5d1faa9d0a254e9d1a",
          "md5": "2a1a583d81672a9a6e7478355243d816"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v149.jar",
          "url": "natives-box2d-desktop-v149.jar",
          "size": 512159,
          "sha512": "f93b004842223ffc71872e7a10b48d6456d7cf559c3f5de017915f6586bc48e9c92d7de3a54995658e61c2a22cd5250e47c98a845fc9b22ef9d93e76bdfd1bce",
          "sha256": "0153e61fb084d7cec918f5ba0f7f968058c5d840f6a6affb39fa772ffb8108ae",
          "sha1": "b62942acd549f2b495547d5d1faa9d0a254e9d1a",
          "md5": "2a1a583d81672a9a6e7478355243d816"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v149-sources.jar",
          "url": "natives-box2d-desktop-v149-sources.jar",
          "size": 512159,
          "sha512": "5afc63998b91b2d4265bd12389090fd63f91c267a2c6046dfae31364a49cb1805a56be0feedac499a88a657c9ec7f8c9cd31fac7cec6e8c90a8a2eebad5813ca",
          "sha256": "9e711b2d9fc8419f871d2ac5ca8c4444f69294a25908d349d8749618df770336",
          "sha1": "b1dbb9883a31bf73f8dbe5d4f429ca3cac0aaaa8",
          "md5": "77e975a9a01610c0fb14f561d6e9a5dc"
        }
      ]
    }
  ]
}
