{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v156.1.jar",
          "url": "backend-sdl-v156.1.jar",
          "size": 3020500,
          "sha512": "f22d30c01072a6fa71a4a6b961e50986ea9d97bd296c493ad5423e42dd939b0efd07ceff661d557d7da6706b05674112125e8f4c3de361b9894cceea5265267e",
          "sha256": "e2d5aab0a7f1747fcdb40ce151e93a784a81e2b8468a77691093839bce539aea",
          "sha1": "15bd85760450527f7ae90c4e20db63d522dd9059",
          "md5": "560e593a87bd9a521179491ac700c691"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v156.1.jar",
          "url": "backend-sdl-v156.1.jar",
          "size": 3020500,
          "sha512": "f22d30c01072a6fa71a4a6b961e50986ea9d97bd296c493ad5423e42dd939b0efd07ceff661d557d7da6706b05674112125e8f4c3de361b9894cceea5265267e",
          "sha256": "e2d5aab0a7f1747fcdb40ce151e93a784a81e2b8468a77691093839bce539aea",
          "sha1": "15bd85760450527f7ae90c4e20db63d522dd9059",
          "md5": "560e593a87bd9a521179491ac700c691"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v156.1-sources.jar",
          "url": "backend-sdl-v156.1-sources.jar",
          "size": 3001408,
          "sha512": "8545f97122ad6c1620a8f55700dc6fa041d6ddd59257ed3bc9607b2bdc7589d04e85e6ab54b07a3b948a9a4e289b5db769970f5850de83e3b54843d11c3c77ef",
          "sha256": "c3bcc38e2fbbed7706ada7699590f52b4927e33dcac02cf0b729624b5f8156ac",
          "sha1": "9da9744e64f5c71a816a8c659fd6998030deb3e8",
          "md5": "9ca9b7282fc4fce33c376950c0cd8194"
        }
      ]
    }
  ]
}
