{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v156.1.jar",
          "url": "backend-sdl-v156.1.jar",
          "size": 3020500,
          "sha512": "ddd0b8c5f5e2d01442fd4d740a30241de633a250900fb9a743192d3ac4fb77a94b08421a4f238755af9eba829e98647b87398816e7788dbe0c28864d3c83f5a0",
          "sha256": "2047f1c5cf7f61c2fff21059243f369c86d936e7a33ed884b8dfacd6e3f3f0d0",
          "sha1": "90558d9ebddee0b27628227bba526656b42d0982",
          "md5": "e8332d4853fb685211f466374b4b32d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v156.1.jar",
          "url": "backend-sdl-v156.1.jar",
          "size": 3020500,
          "sha512": "ddd0b8c5f5e2d01442fd4d740a30241de633a250900fb9a743192d3ac4fb77a94b08421a4f238755af9eba829e98647b87398816e7788dbe0c28864d3c83f5a0",
          "sha256": "2047f1c5cf7f61c2fff21059243f369c86d936e7a33ed884b8dfacd6e3f3f0d0",
          "sha1": "90558d9ebddee0b27628227bba526656b42d0982",
          "md5": "e8332d4853fb685211f466374b4b32d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v156.1-sources.jar",
          "url": "backend-sdl-v156.1-sources.jar",
          "size": 3001408,
          "sha512": "422fee2d19b8dd8068c88b19bab11f3f43bc89aa7bac5e6f73ff4a5fb426d86bc04ef87717ee9f2415ef2afc5d35d345a05e3ebdf4b2aeaa764706efbf94a6af",
          "sha256": "7238365f1769fb0f665c8804aeac213832c5b8292de6adae8d8cace806574325",
          "sha1": "9832e7b5f3911efe5084465c7e99cc81aaca0496",
          "md5": "e1c8a4c3eff4fe56e356ee8c15a9e6d0"
        }
      ]
    }
  ]
}
