{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v154.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v154.2.jar",
          "url": "natives-box2d-android-v154.2.jar",
          "size": 411485,
          "sha512": "5f54219e5224182a620306d15f69a1da7b7379ce8894f310473f637c4d9175c6bef5b97c43309e7ba9d6528d6ccd037ca2a432d1175b4e118f1056abdd38138a",
          "sha256": "975cf6640e54dbf8ed0ccafdb42a31a050351082fe11b678e09920dbb8ea86ac",
          "sha1": "605b5135205308aa50e2768a5cb821bd2e039566",
          "md5": "fde1354be8bd0993b6196d8088c6170d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v154.2.jar",
          "url": "natives-box2d-android-v154.2.jar",
          "size": 411485,
          "sha512": "5f54219e5224182a620306d15f69a1da7b7379ce8894f310473f637c4d9175c6bef5b97c43309e7ba9d6528d6ccd037ca2a432d1175b4e118f1056abdd38138a",
          "sha256": "975cf6640e54dbf8ed0ccafdb42a31a050351082fe11b678e09920dbb8ea86ac",
          "sha1": "605b5135205308aa50e2768a5cb821bd2e039566",
          "md5": "fde1354be8bd0993b6196d8088c6170d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v154.2-sources.jar",
          "url": "natives-box2d-android-v154.2-sources.jar",
          "size": 411485,
          "sha512": "816cf48c6740bc716c4f6cbb6848e93ea8677d0cf519467c9510122435f56ebc0ade613e48ad2a3885b0d97627a7305b1af2d4a858debdabc1d7bd866d108404",
          "sha256": "fba778aa884a3b52a98011fdf7019f5c69e25ce0692c2009b3fa458be7e8201e",
          "sha1": "3f52cae6b785cd64fce1698832a9261c4df48231",
          "md5": "fab1d6eb2d718268a594d0e8341a4f49"
        }
      ]
    }
  ]
}
