{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-v156.1.jar",
          "url": "natives-v156.1.jar",
          "size": 261,
          "sha512": "9f703547709587fa3df3a290037ee85d71d5409bf44f2ca95f616772e7a053c38761d9a5e80805f316d71b76d4264f18a32d1d04c4d32b4680f7ba3342bf5f41",
          "sha256": "8291eaa4ed5f586e6f6cfa6f997d278ff9d03d7b823e20a09efe581bf6e2130c",
          "sha1": "ab808648792712c73da4eb92beaa464dd518f4ae",
          "md5": "9934673e2a35d909c28ad995af5dc42c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-v156.1.jar",
          "url": "natives-v156.1.jar",
          "size": 261,
          "sha512": "9f703547709587fa3df3a290037ee85d71d5409bf44f2ca95f616772e7a053c38761d9a5e80805f316d71b76d4264f18a32d1d04c4d32b4680f7ba3342bf5f41",
          "sha256": "8291eaa4ed5f586e6f6cfa6f997d278ff9d03d7b823e20a09efe581bf6e2130c",
          "sha1": "ab808648792712c73da4eb92beaa464dd518f4ae",
          "md5": "9934673e2a35d909c28ad995af5dc42c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-v156.1-sources.jar",
          "url": "natives-v156.1-sources.jar",
          "size": 261,
          "sha512": "9f703547709587fa3df3a290037ee85d71d5409bf44f2ca95f616772e7a053c38761d9a5e80805f316d71b76d4264f18a32d1d04c4d32b4680f7ba3342bf5f41",
          "sha256": "8291eaa4ed5f586e6f6cfa6f997d278ff9d03d7b823e20a09efe581bf6e2130c",
          "sha1": "ab808648792712c73da4eb92beaa464dd518f4ae",
          "md5": "9934673e2a35d909c28ad995af5dc42c"
        }
      ]
    }
  ]
}
