{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "freetype",
    "version": "v156.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "freetype-v156.1.jar",
          "url": "freetype-v156.1.jar",
          "size": 35563,
          "sha512": "be9d4e596a72f400f7cbfce2239fbc2a0cc7a0cfca6bf56c6b1479a8c5de795a0792787d5cb03f78ca94a6c370897b7c8f38e65db38360ba19959f624889a47d",
          "sha256": "a1066d4a2c2141e20c667db8c2a040f41e73bbf7a96037ed5f1b4a07ff504c7b",
          "sha1": "a1ef57441f3e03af9eab14e41eb694f9fdff48a8",
          "md5": "936697aa93da7624a763d2f0c447d872"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "freetype-v156.1.jar",
          "url": "freetype-v156.1.jar",
          "size": 35563,
          "sha512": "be9d4e596a72f400f7cbfce2239fbc2a0cc7a0cfca6bf56c6b1479a8c5de795a0792787d5cb03f78ca94a6c370897b7c8f38e65db38360ba19959f624889a47d",
          "sha256": "a1066d4a2c2141e20c667db8c2a040f41e73bbf7a96037ed5f1b4a07ff504c7b",
          "sha1": "a1ef57441f3e03af9eab14e41eb694f9fdff48a8",
          "md5": "936697aa93da7624a763d2f0c447d872"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "freetype-v156.1-sources.jar",
          "url": "freetype-v156.1-sources.jar",
          "size": 16761,
          "sha512": "9df2dc33f0525d2853c754b4bc8944c97c55914f199ecec8a0222684868b616e1989a0a0b34f351baed6fcd14763f8df28e8972bce68d9659b6cc7852c1a04d6",
          "sha256": "501c0c35027b69c1e1cfbd6caff88d5f88bb58f25ea2a369a5bed4a82eca1e5e",
          "sha1": "7678777a320b4c19cdc0a7eaee76e14208394f67",
          "md5": "efd461d2c151799b627406385abffa4a"
        }
      ]
    }
  ]
}
