{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v155.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v155.1.jar",
          "url": "backends-v155.1.jar",
          "size": 261,
          "sha512": "87c561e8e808e85d0627c9d73c3bd699722438a4a7eff836b717bac61eef5ac2054710369e909854d44d23a8d10757b6cfa622da47731903c3485b5173da1d7d",
          "sha256": "2d7c99ec300acf8db2c10f38f6db427fe0f4b30f3a1d6216239fa78bd97c8480",
          "sha1": "839acc4fee864d76f018afe8151952acd0aa322c",
          "md5": "bb546485c49ada1a95f7b78f715bcc22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v155.1.jar",
          "url": "backends-v155.1.jar",
          "size": 261,
          "sha512": "87c561e8e808e85d0627c9d73c3bd699722438a4a7eff836b717bac61eef5ac2054710369e909854d44d23a8d10757b6cfa622da47731903c3485b5173da1d7d",
          "sha256": "2d7c99ec300acf8db2c10f38f6db427fe0f4b30f3a1d6216239fa78bd97c8480",
          "sha1": "839acc4fee864d76f018afe8151952acd0aa322c",
          "md5": "bb546485c49ada1a95f7b78f715bcc22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v155.1-sources.jar",
          "url": "backends-v155.1-sources.jar",
          "size": 261,
          "sha512": "87c561e8e808e85d0627c9d73c3bd699722438a4a7eff836b717bac61eef5ac2054710369e909854d44d23a8d10757b6cfa622da47731903c3485b5173da1d7d",
          "sha256": "2d7c99ec300acf8db2c10f38f6db427fe0f4b30f3a1d6216239fa78bd97c8480",
          "sha1": "839acc4fee864d76f018afe8151952acd0aa322c",
          "md5": "bb546485c49ada1a95f7b78f715bcc22"
        }
      ]
    }
  ]
}
