{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v150.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v150.1.jar",
          "url": "backends-v150.1.jar",
          "size": 261,
          "sha512": "5fb8d1eef7aefc3300a4cdb86854ee078b825837d42fbe1edc0e81dea5ed9dc6eae6d29a306f2a7b4f4532784e3fd836f99ece4bc0e9ca546e503d6a6a4b435d",
          "sha256": "c70d954c04a0741deea37e2ed1585f73c75caaa680d99a1aec651aebb01a5599",
          "sha1": "692934644fc463e4049820210140f7a51d4833cd",
          "md5": "90fe83cee11b371dd4c1cc51cdc9adf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v150.1.jar",
          "url": "backends-v150.1.jar",
          "size": 261,
          "sha512": "5fb8d1eef7aefc3300a4cdb86854ee078b825837d42fbe1edc0e81dea5ed9dc6eae6d29a306f2a7b4f4532784e3fd836f99ece4bc0e9ca546e503d6a6a4b435d",
          "sha256": "c70d954c04a0741deea37e2ed1585f73c75caaa680d99a1aec651aebb01a5599",
          "sha1": "692934644fc463e4049820210140f7a51d4833cd",
          "md5": "90fe83cee11b371dd4c1cc51cdc9adf9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v150.1-sources.jar",
          "url": "backends-v150.1-sources.jar",
          "size": 261,
          "sha512": "5fb8d1eef7aefc3300a4cdb86854ee078b825837d42fbe1edc0e81dea5ed9dc6eae6d29a306f2a7b4f4532784e3fd836f99ece4bc0e9ca546e503d6a6a4b435d",
          "sha256": "c70d954c04a0741deea37e2ed1585f73c75caaa680d99a1aec651aebb01a5599",
          "sha1": "692934644fc463e4049820210140f7a51d4833cd",
          "md5": "90fe83cee11b371dd4c1cc51cdc9adf9"
        }
      ]
    }
  ]
}
