{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v152.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v152.1.jar",
          "url": "natives-box2d-android-v152.1.jar",
          "size": 411485,
          "sha512": "350b77de0d8e2a2b85a7da0afd418b617a5d48db52ce2156ac24aa040d347443f8b7e00ced2d492290ab91d990ab9ae21ac6ac0eed7c6ff65e4c9682a0e7cc03",
          "sha256": "4057c74c2e775e5b6c9b4793c4fa9f953200f5894e0825597222af1cf9994dc2",
          "sha1": "83e5d9cc25bf60affe25403561c9129e96f1cb5e",
          "md5": "10e5517a752aaede45202cdf20e89180"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v152.1.jar",
          "url": "natives-box2d-android-v152.1.jar",
          "size": 411485,
          "sha512": "350b77de0d8e2a2b85a7da0afd418b617a5d48db52ce2156ac24aa040d347443f8b7e00ced2d492290ab91d990ab9ae21ac6ac0eed7c6ff65e4c9682a0e7cc03",
          "sha256": "4057c74c2e775e5b6c9b4793c4fa9f953200f5894e0825597222af1cf9994dc2",
          "sha1": "83e5d9cc25bf60affe25403561c9129e96f1cb5e",
          "md5": "10e5517a752aaede45202cdf20e89180"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v152.1-sources.jar",
          "url": "natives-box2d-android-v152.1-sources.jar",
          "size": 411485,
          "sha512": "7ee41d4171d6b40cca8e32fdb7365d6e7d32c47e02d6cca8a5ebbf517879a46d38cd56a6b32b18c63399a16e57e295db9a5c0ab215ec994c5698426c9bd9d699",
          "sha256": "00274f9afc9c26df6ece0ae7eed0616b40921c808e1a1db59a0c5f4f75d68b68",
          "sha1": "e85b54215d7a686d81408ccefe563eab103823bb",
          "md5": "9a384dda621b23f8846212ba7f4cb37d"
        }
      ]
    }
  ]
}
