{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v154.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v154.3.jar",
          "url": "backends-v154.3.jar",
          "size": 261,
          "sha512": "c0cb9e4605b57af56d964a42b47a16c128ef01e63ca9f17f89ccc41e447884a888914edb6ee26fe30f181879257b664bc0010a799f8ba93e8b5232708bcb275f",
          "sha256": "7c54784a9f6415438ac7dffe23e9464b49a58d7ffe4211d8d9c66bec7779d64b",
          "sha1": "dee5eea9b552ac20c06d6f13777da68c11c2bf6b",
          "md5": "8eba6f899085625fde85ffd4a1d3285c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v154.3.jar",
          "url": "backends-v154.3.jar",
          "size": 261,
          "sha512": "c0cb9e4605b57af56d964a42b47a16c128ef01e63ca9f17f89ccc41e447884a888914edb6ee26fe30f181879257b664bc0010a799f8ba93e8b5232708bcb275f",
          "sha256": "7c54784a9f6415438ac7dffe23e9464b49a58d7ffe4211d8d9c66bec7779d64b",
          "sha1": "dee5eea9b552ac20c06d6f13777da68c11c2bf6b",
          "md5": "8eba6f899085625fde85ffd4a1d3285c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v154.3-sources.jar",
          "url": "backends-v154.3-sources.jar",
          "size": 261,
          "sha512": "c0cb9e4605b57af56d964a42b47a16c128ef01e63ca9f17f89ccc41e447884a888914edb6ee26fe30f181879257b664bc0010a799f8ba93e8b5232708bcb275f",
          "sha256": "7c54784a9f6415438ac7dffe23e9464b49a58d7ffe4211d8d9c66bec7779d64b",
          "sha1": "dee5eea9b552ac20c06d6f13777da68c11c2bf6b",
          "md5": "8eba6f899085625fde85ffd4a1d3285c"
        }
      ]
    }
  ]
}
