{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v152",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v152.jar",
          "url": "natives-freetype-desktop-v152.jar",
          "size": 1098026,
          "sha512": "fbc70da45f6efeb4c40b1e5ff95761873b87df7a5ccb3e73c057ed77a8978f88391217e75308a2110c9f66a27751e2aa5df8cdb8bb684deed3b85d3b6d85e563",
          "sha256": "cefe999d1dda2a077042ff4f16f7be55e6f267c63dd40f699400126389afbd6b",
          "sha1": "98b7c9bff33af5dfc27cab2a52ba0f74f96c1f8c",
          "md5": "2f7f1b3e09a3e727e047e333ceeff283"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v152.jar",
          "url": "natives-freetype-desktop-v152.jar",
          "size": 1098026,
          "sha512": "fbc70da45f6efeb4c40b1e5ff95761873b87df7a5ccb3e73c057ed77a8978f88391217e75308a2110c9f66a27751e2aa5df8cdb8bb684deed3b85d3b6d85e563",
          "sha256": "cefe999d1dda2a077042ff4f16f7be55e6f267c63dd40f699400126389afbd6b",
          "sha1": "98b7c9bff33af5dfc27cab2a52ba0f74f96c1f8c",
          "md5": "2f7f1b3e09a3e727e047e333ceeff283"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v152-sources.jar",
          "url": "natives-freetype-desktop-v152-sources.jar",
          "size": 1098026,
          "sha512": "f285de0513133d336f49b829c742919a89b17c7a477fedd6aab10829058b4239451f461ca972068d2f2ba89f7b688c21e6c5f0174edf5f2c7d8ba01548d8c93d",
          "sha256": "ec2a9d5889471bc60f51d7670ce691f9e68c801f4754efee5eaed1d77aaab6a8",
          "sha1": "fc63b7e0ab091d46c5ee0e127ff01156c01ce054",
          "md5": "647d0dc6dfb83820ba445dbdabcae330"
        }
      ]
    }
  ]
}
